<a href="https://colab.research.google.com/github/Afkar5115/Kecerdasan_Buatan_TI-1B_2025/blob/main/Jobsheet_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 5 PENGAMBILAN DAN PEMBERSIHAN DATA MENGGUNAKAN PANDAS

## Latihan

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Data.csv')
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0         NaN        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung     NaN   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

In [ ]:
df.isnull().sum()

Negara       0
Umur         1
Gaji         1
Transaksi    0
dtype: int64

### 1.Hapus Data yang kosong (NaN)

In [ ]:
df = pd.read_csv('./Data.csv')
df.dropna(inplace=True)

df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
5   Jakarta    35.0  10000000.0        Ya
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 2.Ganti Data yang kosong (NaN) menjadi :

### <ul><li>Umur = 50 </li><li>Gaji = 25000000</li></ul>

In [ ]:
df = pd.read_csv('./Data.csv')
df['Umur'].fillna(50, inplace=True)
df['Gaji'].fillna(25000000, inplace=True)
df

<ipython-input-12-cefa89afd30c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(50, inplace=True)
<ipython-input-12-cefa89afd30c>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(25000000, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0  25000000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    50.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 3.Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Rata-Rata

In [ ]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].mean();
mean_gaji = df['Gaji'].mean();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)
df

<ipython-input-13-6b88f0aebe06>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-13-6b88f0aebe06>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara         Umur          Gaji Transaksi
0   Jakarta    44.000000  8.000000e+06     Tidak
1   Bandung    27.000000  6.700000e+06        Ya
2  Surabaya    30.000000  4.500000e+06     Tidak
3   Bandung    38.000000  7.500000e+06     Tidak
4  Surabaya    40.000000  7.674889e+06        Ya
5   Jakarta    35.000000  1.000000e+07        Ya
6   Bandung   143.222222  8.250000e+06     Tidak
7   Jakarta    48.000000  9.750000e+06        Ya
8  Surabaya  1000.000000  7.674000e+06     Tidak
9   Jakarta    27.000000  6.700000e+06        Ya

### 4.Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Median

In [ ]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].median();
mean_gaji = df['Gaji'].median();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-14-3f09d7a429bc>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-14-3f09d7a429bc>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   7674000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    38.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 5. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Modus

In [ ]:
df = pd.read_csv('Data.csv')
mean_umur = df['Umur'].mode()[0];
mean_gaji = df['Gaji'].mode()[0];

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-17-38b9ffbd5f4b>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-17-38b9ffbd5f4b>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   6700000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    27.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 6. Apabila Ada Umur yang diatas 120 maka ubah menjadi 33

In [ ]:
df = pd.read_csv('./Data.csv')

for x in df.index:
    if df.loc[x, 'Umur'] > 120:
        df.loc[x, 'Umur'] = 33

df

     Negara  Umur        Gaji Transaksi
0   Jakarta  44.0   8000000.0     Tidak
1   Bandung  27.0   6700000.0        Ya
2  Surabaya  30.0   4500000.0     Tidak
3   Bandung  38.0   7500000.0     Tidak
4  Surabaya  40.0         NaN        Ya
5   Jakarta  35.0  10000000.0        Ya
6   Bandung   NaN   8250000.0     Tidak
7   Jakarta  48.0   9750000.0        Ya
8  Surabaya  33.0   7674000.0     Tidak
9   Jakarta  27.0   6700000.0        Ya

## Praktikum

### 1.Buatlah table list Top 5 Customers yang memiliki nilai transaksi paling banyak !

In [5]:
import pandas as pd

def load_transactions_data():
    """Memuat dan mempersiapkan data transaksi dari file CSV"""
    try:
        # Memuat data transaksi
        transactions_df = pd.read_csv('transactions_1k.csv')

        # Persiapan data transaksi
        transactions_df['DateTime'] = pd.to_datetime(transactions_df['Date'] + ' ' + transactions_df['Time'])
        transactions_df['Hour'] = transactions_df['DateTime'].dt.hour

        return transactions_df
    except FileNotFoundError as e:
        print(f"Error: File tidak ditemukan - {e}")
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None

def analyze_top_transactions(transactions_df):
    """Analisis dan tampilkan 5 transaksi dengan jumlah pembelian terbanyak"""
    if transactions_df is not None:
        print("\n=== 5 TRANSAKSI DENGAN JUMLAH PEMBELIAN TERBANYAK ===")

        # Ambil 5 transaksi dengan Amount terbesar
        top_transactions = transactions_df.nlargest(5, 'Amount')


        print(top_transactions[['TransactionID', 'CustomerID', 'ProductID', 'Amount', 'Price', 'DateTime']].to_string(index=False))

def main():
    """Fungsi utama untuk menjalankan analisis"""


    # Memuat data transaksi
    transactions_df = load_transactions_data()

    # Jalankan analisis
    analyze_top_transactions(transactions_df)



if __name__ == "__main__":
    main()

=== 5 TRANSAKSI DENGAN JUMLAH PEMBELIAN TERBANYAK ===
 TransactionID  CustomerID  ProductID  Amount   Price            DateTime
            43       13665          2     264 5762.49 2012-08-24 12:42:00
           859        7938          9     154 3600.84 2012-08-25 10:25:00
           327       39407          2     140 3101.98 2012-08-24 12:31:00
           687       26658          2     137 3090.39 2012-08-25 17:38:00
           568       21312          2     134 3090.45 2012-08-25 09:59:00

### 2.Buatlah list Top 5 Gas stations yang memiliki nilai transaksi paling banyak !

In [7]:
import pandas as pd

# Membaca file CSV
df_gasstations = pd.read_csv("gasstations.csv")
df_transactions = pd.read_csv("transactions_1k.csv")

# Menghitung total nilai transaksi per stasiun
top_gas_stations = df_transactions.groupby("GasStationID")["Price"].sum().sort_values(ascending=False).head(5).reset_index()

# Menggabungkan dengan informasi stasiun
merged_df = pd.merge(top_gas_stations, df_gasstations, on="GasStationID", how="left")

# Menampilkan hasil
print("\n=== 5 TRANSAKSI DENGAN JUMLAH PEMBELIAN TERBANYAK ===")
print(merged_df)

=== 5 TRANSAKSI DENGAN JUMLAH PEMBELIAN TERBANYAK ===
   GasStationID    Price  ChainID Country   Segment
0          4347  8557.94        4     CZE   Premium
1            48  6868.67        4     CZE   Premium
2          3250  6744.47       24     CZE  Discount
3          1155  6701.69        4     CZE   Premium
4          2417  6065.16        2     CZE    Noname

### 3.Buatlah list Top 5 Jenis produk yang memiliki nilai transaksi paling banyak !

In [8]:
import pandas as pd

# Membaca data produk
products = pd.read_csv('products.csv')

# Membaca data transaksi
transactions = pd.read_csv('transactions_1k.csv')

# Menghitung total nilai transaksi (Amount * Price) untuk setiap transaksi
transactions['TotalValue'] = transactions['Amount'] * transactions['Price']

# Menggabungkan data transaksi dengan data produk
merged_data = pd.merge(transactions, products, on='ProductID', how='left')

# Menghitung total nilai transaksi per produk
product_sales = merged_data.groupby(['ProductID', 'Description'])['TotalValue'].sum().reset_index()

# Mengurutkan berdasarkan nilai transaksi terbesar
top_5_products = product_sales.sort_values('TotalValue', ascending=False).head(5)

# Menampilkan hasil
print("Top 5 Jenis Produk dengan Nilai Transaksi Terbanyak:")
print(top_5_products[['Description', 'TotalValue']].to_string(index=False))

Top 5 Jenis Produk dengan Nilai Transaksi Terbanyak:
Description  TotalValue
      Nafta 15140539.95
   Diesel +  1545812.01
  Natural +   256837.64
 Nafta Plus   206832.62
    Natural   123913.94

### 4.Buatlah deskripsi statistik untuk masing masing hari (23,24,25,26) pada dataset transaction_1k !

In [9]:
import pandas as pd
import datetime as dt

# Load semua dataset
df_customer = pd.read_csv('customers.csv')
df_gasstation = pd.read_csv('gasstations.csv')
df_product = pd.read_csv('products.csv')
df_transaction = pd.read_csv('transactions_1k.csv')
df_yearmonth = pd.read_csv('yearmonth.csv')

# Merge semua tabel
df_merged = df_transaction.merge(
    df_customer, on='CustomerID', how='left'
).merge(
    df_gasstation, on='GasStationID', how='left'
).merge(
    df_product, on='ProductID', how='left'
)

# 1. Pastikan kolom Date sudah datetime
df_merged['Date'] = pd.to_datetime(df_merged['Date'])

# 2. Filter tanggal 23-26 Agustus 2012
df_filtered = df_merged[
    df_merged['Date'].isin(pd.to_datetime(['2012-08-23', '2012-08-24', '2012-08-25', '2012-08-26']))
]

# 3. Hitung statistik dengan sintaks yang benar
daily_stats = df_filtered.groupby('Date').agg(
    Amount_count=('Amount', 'count'),
    Amount_mean=('Amount', 'mean'),
    Amount_std=('Amount', 'std'),
    Amount_min=('Amount', 'min'),
    Amount_q1=('Amount', lambda x: x.quantile(0.25)),
    Amount_median=('Amount', 'median'),
    Amount_q3=('Amount', lambda x: x.quantile(0.75)),
    Amount_max=('Amount', 'max'),
    Sales_count=('Price', 'count'),
    Sales_mean=('Price', 'mean'),
    Sales_std=('Price', 'std'),
    Sales_min=('Price', 'min'),
    Sales_q1=('Price', lambda x: x.quantile(0.25)),
    Sales_median=('Price', 'median'),
    Sales_q3=('Price', lambda x: x.quantile(0.75)),
    Sales_max=('Price', 'max')
)

# Tampilkan hasil
daily_stats

,Amount_count,Amount_mean,Amount_std,Amount_min,Amount_q1,Amount_median,Amount_q3,Amount_max,Sales_count,Sales_mean,Sales_std,Sales_min,Sales_q1,Sales_median,Sales_q3,Sales_max
Date,,,,,,,,,,,,,,,,
2012-08-23,10,29.600000,24.900692,1,21.25,26.5,35.25,91,10,685.379000,534.046487,76.42,481.170,619.44,795.095,1994.71
2012-08-24,492,19.936992,21.949630,0,5.00,19.0,27.00,264,492,409.939736,488.269481,1.76,76.125,332.45,615.395,5762.49
2012-08-25,425,18.880000,20.376114,0,4.00,17.0,26.00,154,425,426.940071,453.134207,6.09,102.220,370.38,600.850,3600.84
2012-08-26,73,21.219178,18.932810,0,6.00,20.0,29.00,101,73,487.431370,429.192499,4.74,142.840,437.03,675.520,2303.75

### 5.Carilah waktu terbaik (hari dan jam) dimana paling banyak user gas station melakukan transaksi !

In [12]:
import pandas as pd
import datetime as dt

# Load semua dataset
df_customer = pd.read_csv('customers.csv')
df_gasstation = pd.read_csv('gasstations.csv')
df_product = pd.read_csv('products.csv')
df_transaction = pd.read_csv('transactions_1k.csv')
df_yearmonth = pd.read_csv('yearmonth.csv')

# Merge semua tabel
df_merged = df_transaction.merge(
    df_customer, on='CustomerID', how='left'
).merge(
    df_gasstation, on='GasStationID', how='left'
).merge(
    df_product, on='ProductID', how='left'
)

# Konversi tipe data waktu
df_merged['Date'] = pd.to_datetime(df_merged['Date'])
df_merged['Hour'] = pd.to_datetime(df_merged['Time']).dt.hour

# Ekstrak jam dari kolom Time
df_merged['Hour'] = pd.to_datetime(df_merged['Time']).dt.hour

# Group by Date dan Hour, lalu hitung total Amount dan Price
best_time = df_merged.groupby(['Date', 'Hour']).agg({
    'Amount': 'sum',
    'Price': 'sum'
}).sort_values('Amount', ascending=False).head(5)

# Rename kolom Price menjadi Gas Sales
best_time = best_time.rename(columns={'Price': 'Gas Sales'})

# Tampilkan hasil
best_time

<ipython-input-12-31d057a7c055>:22: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_merged['Hour'] = pd.to_datetime(df_merged['Time']).dt.hour
<ipython-input-12-31d057a7c055>:25: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_merged['Hour'] = pd.to_datetime(df_merged['Time']).dt.hour

                 Amount  Gas Sales
Date       Hour
2012-08-25 9       1034   19362.21
2012-08-24 16      1007   23528.20
2012-08-25 11      1001   23105.06
2012-08-24 14       998   20553.11
           12       962   20225.78