<a href="https://colab.research.google.com/github/Afkar5115/Kecerdasan_Buatan_TI-1B_2025/blob/main/Jobsheet_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 5 PENGAMBILAN DAN PEMBERSIHAN DATA MENGGUNAKAN PANDAS

## Latihan

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Data.csv')
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0         NaN        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung     NaN   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

In [ ]:
df.isnull().sum()

Negara       0
Umur         1
Gaji         1
Transaksi    0
dtype: int64

### 1.Hapus Data yang kosong (NaN)

In [ ]:
df = pd.read_csv('./Data.csv')
df.dropna(inplace=True)

df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
5   Jakarta    35.0  10000000.0        Ya
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 2.Ganti Data yang kosong (NaN) menjadi :

### <ul><li>Umur = 50 </li><li>Gaji = 25000000</li></ul>

In [ ]:
df = pd.read_csv('./Data.csv')
df['Umur'].fillna(50, inplace=True)
df['Gaji'].fillna(25000000, inplace=True)
df

<ipython-input-12-cefa89afd30c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(50, inplace=True)
<ipython-input-12-cefa89afd30c>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(25000000, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0  25000000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    50.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 3.Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Rata-Rata

In [ ]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].mean();
mean_gaji = df['Gaji'].mean();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)
df

<ipython-input-13-6b88f0aebe06>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-13-6b88f0aebe06>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara         Umur          Gaji Transaksi
0   Jakarta    44.000000  8.000000e+06     Tidak
1   Bandung    27.000000  6.700000e+06        Ya
2  Surabaya    30.000000  4.500000e+06     Tidak
3   Bandung    38.000000  7.500000e+06     Tidak
4  Surabaya    40.000000  7.674889e+06        Ya
5   Jakarta    35.000000  1.000000e+07        Ya
6   Bandung   143.222222  8.250000e+06     Tidak
7   Jakarta    48.000000  9.750000e+06        Ya
8  Surabaya  1000.000000  7.674000e+06     Tidak
9   Jakarta    27.000000  6.700000e+06        Ya

### 4.Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Median

In [ ]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].median();
mean_gaji = df['Gaji'].median();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-14-3f09d7a429bc>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-14-3f09d7a429bc>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   7674000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    38.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 5. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Modus

In [ ]:
df = pd.read_csv('Data.csv')
mean_umur = df['Umur'].mode()[0];
mean_gaji = df['Gaji'].mode()[0];

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-17-38b9ffbd5f4b>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-17-38b9ffbd5f4b>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   6700000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    27.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

### 6. Apabila Ada Umur yang diatas 120 maka ubah menjadi 33

In [ ]:
df = pd.read_csv('./Data.csv')

for x in df.index:
    if df.loc[x, 'Umur'] > 120:
        df.loc[x, 'Umur'] = 33

df

     Negara  Umur        Gaji Transaksi
0   Jakarta  44.0   8000000.0     Tidak
1   Bandung  27.0   6700000.0        Ya
2  Surabaya  30.0   4500000.0     Tidak
3   Bandung  38.0   7500000.0     Tidak
4  Surabaya  40.0         NaN        Ya
5   Jakarta  35.0  10000000.0        Ya
6   Bandung   NaN   8250000.0     Tidak
7   Jakarta  48.0   9750000.0        Ya
8  Surabaya  33.0   7674000.0     Tidak
9   Jakarta  27.0   6700000.0        Ya

## Praktikum

### 1.Buatlah table list Top 5 Customers yang memiliki nilai transaksi paling banyak !

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style untuk visualisasi
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

def load_and_prepare_data():
    """Memuat dan mempersiapkan data dari file CSV"""
    try:
        # Memuat data
        customers_df = pd.read_csv('customers.csv')
        transactions_df = pd.read_csv('transactions_1k.csv')

        # Persiapan data transaksi
        transactions_df['DateTime'] = pd.to_datetime(transactions_df['Date'] + ' ' + transactions_df['Time'])
        transactions_df['Hour'] = transactions_df['DateTime'].dt.hour

        # Gabungkan data pelanggan dengan transaksi
        customer_transactions = transactions_df.groupby('CustomerID').agg(
            TotalTransactions=('TransactionID', 'count'),
            TotalAmount=('Amount', 'sum'),
            TotalSpent=('Price', 'sum')
        ).reset_index()

        full_customer_data = customers_df.merge(customer_transactions, on='CustomerID', how='left')

        return full_customer_data, transactions_df
    except FileNotFoundError as e:
        print(f"Error: File tidak ditemukan - {e}")
        return None, None
    except Exception as e:
        print(f"Error: {e}")
        return None, None

def analyze_customers(customers_df):
    """Analisis data pelanggan"""
    print("\n=== ANALISIS PELANGGAN ===")

    # Top 5 pelanggan berdasarkan jumlah transaksi
    top_by_transactions = customers_df.sort_values('TotalTransactions', ascending=False).head(5)
    print("\nTop 5 Pelanggan berdasarkan Jumlah Transaksi:")
    print(top_by_transactions[['CustomerID', 'Segment', 'TotalTransactions']].to_string(index=False))

    # Top 5 pelanggan berdasarkan total pengeluaran
    top_by_spending = customers_df.sort_values('TotalSpent', ascending=False).head(5)
    print("\nTop 5 Pelanggan berdasarkan Total Pengeluaran:")
    print(top_by_spending[['CustomerID', 'Segment', 'TotalSpent']].to_string(index=False))

    # Simpan hasil analisis
    top_by_transactions.to_csv('top_customers_by_transactions.csv', index=False)
    top_by_spending.to_csv('top_customers_by_spending.csv', index=False)

def analyze_transactions(transactions_df):
    """Analisis data transaksi - hanya menampilkan 5 transaksi terbanyak"""
    print("\n=== ANALISIS 5 TRANSAKSI TERBANYAK ===")

    # Ambil 5 transaksi dengan Amount terbesar
    top_transactions = transactions_df.nlargest(5, 'Amount')

    print("\n5 Transaksi dengan Jumlah Pembelian Terbanyak:")
    print(top_transactions[['TransactionID', 'CustomerID', 'ProductID', 'Amount', 'Price', 'DateTime']].to_string(index=False))

    # Visualisasi
    plt.figure(figsize=(12, 6))
    sns.barplot(x='TransactionID', y='Amount', data=top_transactions, palette='viridis')
    plt.title('5 Transaksi dengan Jumlah Pembelian Terbanyak')
    plt.xlabel('ID Transaksi')
    plt.ylabel('Jumlah Pembelian (liter)')
    plt.xticks(rotation=45)
    plt.show()

def main():
    """Fungsi utama untuk menjalankan analisis"""
    print("Memulai analisis data pelanggan dan transaksi...")

    # Memuat data
    customers_df, transactions_df = load_and_prepare_data()

    if customers_df is not None and transactions_df is not None:
        # Jalankan analisis
        analyze_customers(customers_df)
        analyze_transactions(transactions_df)

    print("\nAnalisis selesai. Hasil telah disimpan dalam file CSV.")

if __name__ == "__main__":
    main()

Memulai analisis data pelanggan dan transaksi...
Error: File tidak ditemukan - [Errno 2] No such file or directory: 'customers.csv'

Analisis selesai. Hasil telah disimpan dalam file CSV.

### 2.Buatlah list Top 5 Gas stations yang memiliki nilai transaksi paling banyak !

### 3.Buatlah list Top 5 Jenis produk yang memiliki nilai transaksi paling banyak !

### 4.Buatlah deskripsi statistik untuk masing masing hari (23,24,25,26) pada dataset transaction_1k !

### 5.Carilah waktu terbaik (hari dan jam) dimana paling banyak user gas station melakukan transaksi !