<a href="https://colab.research.google.com/github/Afkar5115/Kecerdasan_Buatan_TI-1B_2025/blob/main/Jobsheet_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 4 : PENGOLAHAN DATA MENGGUNAKAN PANDAS

## Latihan

###  1.Membaca berbagai format file menggunakan Pandas

#### a.	Membaca file CSV

In [ ]:
import pandas as pd

df = pd.read_csv('./data.csv')
print(df.to_string())

pd
pd.options.display.max_rows

pd.options.display.max_rows = 9999

df = pd.read_csv('./data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### b.	Membaca file JSON

In [ ]:
import pandas as pd

df = pd.read_json('./data.json')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### c.	Menggunakan Parameter pada Pandas Read

In [ ]:
df = pd.read_csv('./data.csv', sep=',', header=0)
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### d.	Membaca Custom Data

In [ ]:
data = {
  "Duration": {
    "0": 60,
    "1": 60,
    "2": 60,
    "3": 45
  },
  "Pulse": {
    "0": 110,
    "1": 117,
    "2": 103,
    "3": 109
  },
  "Maxpulse": {
    "0": 130,
    "1": 145,
    "2": 135,
    "3": 175
  },
  "Calories": {
    "0": 409,
    "1": 479,
    "2": 340,
    "3": 282
  }
}

df = pd.DataFrame(data)
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282

### 2.Membuat dan Mengakses Elemen Series

#### a.	Membuat Series dari sebuah List Python

In [ ]:
import pandas as pd

li = [1, 7, 2]
se = pd.Series(li)

print(se)

0    1
1    7
2    2
dtype: int64

#### b.	Mengakses Elemen pada Series

In [ ]:
li = [1, 7, 2]
se = pd.Series(li)

print(se[0])

1

#### c.	Memberi Label pada Series

In [ ]:
li = [1, 7, 2]
se = pd.Series(li, index = ['x', 'y', 'z'])

print(se['x'])

1

#### d.	Membuat Series dari Dictionary

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)

print(se)

day1    420
day2    380
day3    390
dtype: int64

### 3.Membuat DataFrame

#### a.	Membuat DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame(data= {"Nama" : ["Ali","Joko","Adi"],
	                       "Umur": [12, 13, 15],
	                       "Kelas": [6, 7, 8]})
df.columns
df.columns.values[0] = "Nama Singkat"
df

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

#### b.	Mengakses Elemen pada DataFrame

In [ ]:
df.iloc[0:2, [0,1]]
df.iloc[0:2, 0:2]
df.iloc[:, 0:2]
df.loc[0:2, :'calories']
df.loc[0:2, ['calories', 'duration']]
df['calories']
df['calories'][0]
df[['calories']]
df[['calories']].loc[[0, 1]]

   calories
0       420
1       380

#### c.	Memberi Nama pada Index

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

      calories  duration
day1       420        50
day2       380        40
day3       390        45

#### d.	Melihat DataFrame

In [ ]:
df = pd.read_csv('./data.csv')
print(df)
df
df.head()
df.tail()
df.head(10)
df.shape
df.dtypes

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

#### e.	Membaca Informasi pada DataFrame

In [ ]:
df.info()
df.describe()
df['Calories'].mean(), df['Calories'].median(), df['Calories'].mode()[0]
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

## Praktikum

### 1.Load dataset “Top Score English Premier League (EPL) musim 2020/2021” dan ubah menjadi dataframe

In [ ]:
import pandas as pd

# Load dataset dari file CSV
df = pd.read_csv("epl-goalScorer(20-21).csv")

# Tampilkan beberapa baris pertama
print(df.head())

   Unnamed: 0    id      player_name  games  time  goals         xG  assists  \
0           0   647       Harry Kane     35  3097     23  22.174859       14
1           1  1250    Mohamed Salah     37  3085     22  20.250847        5
2           2  1228  Bruno Fernandes     37  3117     18  16.019454       12
3           3   453    Son Heung-Min     37  3139     17  11.023287       10
4           4   822  Patrick Bamford     38  3085     17  18.401863        7

          xA  shots  key_passes  yellow_cards  red_cards position  \
0   7.577094    138          49             1          0        F
1   6.528526    126          55             0          0    F M S
2  11.474996    121          95             6          0      M S
3   9.512992     68          75             0          0    F M S
4   3.782247    107          30             3          0      F S

          team_title  npg       npxG    xGChain  xGBuildup
0          Tottenham   19  19.130183  24.995648   4.451257
1          Liverpool   16  15.683834  28.968234   9.800236
2  Manchester United    9   8.407840  26.911412  11.932285
3          Tottenham   16  10.262118  20.671916   6.608751
4              Leeds   15  16.879525  23.394953   4.131796

### 2.Ambil 5 data pertama dari dataset “Top Score English Premier League (EPL) musim 2020/2021”

In [5]:
import pandas as pd

# Membaca dataset
data = pd.read_csv('epl-goalScorer(20-21).csv')

# Memilih kolom yang ingin ditampilkan
selected_columns = [
    'player_name', 'goals', 'assists', 'team_title', 'position', 'games', 'shots', 'yellow_cards', 'red_cards'
]

# Mengambil 5 data pertama dengan kolom yang dipilih
top_5 = data[selected_columns].head(5)

# Mengatur tampilan pandas agar lebih lebar
pd.set_option('display.max_columns', None)  # Menampilkan semua kolom
pd.set_option('display.width', 1000)       # Lebar tampilan
pd.set_option('display.colheader_justify', 'left')  # Rata kiri header

# Menampilkan hasil
print("Top 5 Pencetak Gol EPL 2020/2021:")
print(top_5.to_string(index=False))  # Menghilangkan indeks default

Top 5 Pencetak Gol EPL 2020/2021:
player_name      goals  assists team_title        position  games  shots  yellow_cards  red_cards
     Harry Kane 23     14               Tottenham     F    35     138    1             0
  Mohamed Salah 22      5               Liverpool F M S    37     126    0             0
Bruno Fernandes 18     12       Manchester United   M S    37     121    6             0
  Son Heung-Min 17     10               Tottenham F M S    37      68    0             0
Patrick Bamford 17      7                   Leeds   F S    38     107    3             0

### 3.Tampilkan jumlah baris dan jumlah kolom dari dataset

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Dapatkan jumlah baris dan kolom
rows, cols = df.shape

# Tampilkan hasil
print(" Informasi Dataset EPL 2020/2021")
print(f" Jumlah Baris (Data) : {rows}")
print(f" Jumlah Kolom (Fitur): {cols}")

 Informasi Dataset EPL 2020/2021
 Jumlah Baris (Data) : 522
 Jumlah Kolom (Fitur): 19

### 4.Tampilkan tipe data dari masing-masing kolom dataset

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Tampilkan tipe data dari setiap kolom
print(" Tipe Data Setiap Kolom:")
print(df.dtypes)

 Tipe Data Setiap Kolom:
Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

### 5.Tampilkan jumlah goal yang dicetak setiap pemain yang terdapat di dataset

In [ ]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Menampilkan kolom 'player_name' dan 'goals' saja
goal_scorers = df[['player_name', 'goals']]

# Mengurutkan berdasarkan jumlah goal secara descending
goal_scorers_sorted = goal_scorers.sort_values(by='goals', ascending=False)

# Menampilkan hasil
print("Daftar Jumlah Goal Setiap Pemain:")
print(goal_scorers_sorted.to_string(index=False))

Daftar Jumlah Goal Setiap Pemain:
              player_name  goals
               Harry Kane     23
            Mohamed Salah     22
          Bruno Fernandes     18
          Patrick Bamford     17
            Son Heung-Min     17
    Dominic Calvert-Lewin     16
              Jamie Vardy     15
            Ollie Watkins     14
      Alexandre Lacazette     13
           Ilkay Gündogan     13
               Danny Ings     12
               Chris Wood     12
            Callum Wilson     12
        Kelechi Iheanacho     12
              Gareth Bale     11
            Wilfried Zaha     11
          Marcus Rashford     11
          Matheus Pereira     11
               Sadio Mané     11
             Tomas Soucek     10
        Christian Benteke     10
           Anwar El Ghazi     10
           Edinson Cavani     10
          Michail Antonio     10
          Raheem Sterling     10
Pierre-Emerick Aubameyang     10
            Harvey Barnes      9
          Roberto Firmino      9
            Jesse Lingard      9
                Che Adams      9
               Diogo Jota      9
             Riyad Mahrez      9
            Jack Harrison      8
              Neal Maupay      8
            Stuart Dallas      8
             Nicolas Pepe      8
               Phil Foden      8
              Joe Willock      8
            Gabriel Jesus      8
             Jarrod Bowen      8
        James Ward-Prowse      8
           James Maddison      8
                 Jorginho      7
            Ferrán Torres      7
          Mason Greenwood      7
              Richarlison      7
          Bertrand Traoré      7
         David McGoldrick      7
                  Rodrigo      7
            Jack Grealish      6
                 Raphinha      6
          James Rodríguez      6
         Gylfi Sigurdsson      6
          Youri Tielemans      6
              Mason Mount      6
            Danny Welbeck      6
              Timo Werner      6
            Tammy Abraham      6
               Kurt Zouma      5
               Pedro Neto      5
               Bobby Reid      5
               Lewis Dunk      5
          Kevin De Bruyne      5
              Rúben Neves      5
         Leandro Trossard      5
              Bukayo Saka      5
          Callum Robinson      5
          Ademola Lookman      4
           Miguel Almirón      4
         Stuart Armstrong      4
             Eberechi Eze      4
             Raúl Jiménez      4
            Mateusz Klich      4
              Kai Havertz      4
        Christian Pulisic      4
           Olivier Giroud      4
          Anthony Martial      4
              John Stones      4
          Scott McTominay      4
              Fabio Silva      4
                Joelinton      4
              Pascal Groß      3
      Allan Saint-Maximin      3
             Ross Barkley      3
           Angelo Ogbonna      3
          Ashley Westwood      3
       Jannik Vestergaard      3
              Matej Vydra      3
             Ben Chilwell      3
             Craig Dawson      3
             Kyle Bartley      3
               Paul Pogba      3
            Michael Keane      3
            Pablo Fornals      3
             Theo Walcott      3
           Daniel Podence      3
             Mbaye Diagne      3
              John McGinn      3
          Takumi Minamino      3
              Billy Sharp      3
         Sébastien Haller      3
             Daniel James      3
   Tanguy NDombele Alvaro      3
           Ivan Cavaleiro      3
             Romain Saiss      3
                Josh Maja      3
            Ashley Barnes      3
             Hélder Costa      3
              Lucas Moura      3
      Aleksandar Mitrovic      3
         Timothy Castagne      2
         Ezri Konsa Ngoyo      2
             Jayden Bogle      2
          Conor Gallagher      2
             Hakim Ziyech      2
           Ezgjan Alioski      2
           Aaron Connolly      2
             James Justin      2
       Gabriel Martinelli      2
               Yerry Mina      2
                Trézéguet      2
         Emile Smith-Rowe      2
            Dwight McNeil      2
       Callum Hudson-Odoi      2
            Eddie Nketiah      2
    Pierre-Emile Højbjerg      2
            Sergio Agüero      2
                 Ola Aina      2
          Jeffrey Schlupp      2
         Jamaal Lascelles      2
              Ayoze Pérez      2
      Georginio Wijnaldum      2
           Nathan Redmond      2
              Jonny Evans      2
             Adama Traoré      2
             Tyrone Mings      2
            Marcos Alonso      2
                  Ben Mee      2
  Johann Berg Gudmundsson      2
          Michy Batshuayi      2
            Harry Maguire      2
       Abdoulaye Doucouré      2
            Matt Phillips      2
          Hal Robson-Kanu      2
            Jeff Hendrick      2
   Trent Alexander-Arnold      2
             João Cancelo      2
                    Rodri      2
                Issa Diop      2
             Thiago Silva      2
           Benjamin Mendy      2
             Serge Aurier      2
           Bernardo Silva      2
               Semi Ajayi      2
        Aaron Wan-Bissaka      2
                  Gabriel      2
          Jairo Riedewald      2
              Solly March      2
             Jacob Murphy      2
             Fabian Schär      1
             Granit Xhaka      1
         Thiago Alcántara      1
           Manuel Lanzini      1
          Daniel Jebbison      1
        César Azpilicueta      1
       Ruben Loftus-Cheek      1
              Gary Cahill      1
                  Willian      1
             Dwight Gayle      1
          Marc Albrighton      1
           Daniel Amartey      1
            Jonjo Shelvey      1
          Andros Townsend      1
            Tariq Lamptey      1
       Nathaniel Phillips      1
             Sander Berge      1
          Steven Bergwijn      1
      Alexis Mac Allister      1
             Nathan Tella      1
              Jimmy Dunne      1
            Mason Holgate      1
                Luke Shaw      1
            Tyler Roberts      1
             Keinan Davis      1
             Dennis Praet      1
                  Alisson      1
             Mario Lemina      1
              Emil Krafth      1
           Matthew Lowton      1
             Andy Carroll      1
               Nathan Aké      1
         Jordan Henderson      1
              Kyle Walker      1
        Toby Alderweireld      1
              Erik Lamela      1
              Jordan Ayew      1
          Martin Odegaard      1
            João Moutinho      1
            Said Benrahma      1
          Darnell Furlong      1
             Oliver Burke      1
           Caglar Söyüncü      1
            Wilfred Ndidi      1
         Luka Milivojevic      1
              Declan Rice      1
             Robbie Brady      1
          Virgil van Dijk      1
              Oriol Romeu      1
            Jay Rodriguez      1
             Paul Dummett      1
             Ciaran Clark      1
  Alex Oxlade-Chamberlain      1
           Grady Diangana      1
             Curtis Jones      1
          Rayan Ait Nouri      1
                     Fred      1
                Joe Bryan      1
              Tom Cairney      1
               Willy Boly      1
              Conor Coady      1
       Morgan Gibbs-White      1
          James Tarkowski      1
               David Luiz      1
         Andrew Robertson      1
          Oliver McBurnie      1
          Antonio Rüdiger      1
           Diego Llorente      1
             Willian José      1
          Carlos Vinicius      1
             Adam Webster      1
           Moussa Djenepo      1
               Ben Osborn      1
          Conor Hourihane      1
            Steven Alzate      1
              Reece James      1
           Kieran Tierney      1
          Tyrick Mitchell      1
            Yves Bissouma      1
         Giovani Lo Celso      1
     Jean-Philippe Mateta      1
             Jan Bednarek      1
          Victor Lindelöf      1
         Joachim Andersen      1
              Ben Johnson      1
              Luke Thomas      1
           Pascal Struijk      1
          Kalvin Phillips      1
             Joël Veltman      1
              Liam Cooper      1
        Donny van de Beek      1
               Rúben Dias      1
               Kean Bryan      1
           Fabio Carvalho      1
            Kortney Hause      1
          Ryan Fredericks      1
          Fabián Balbuena      1
                  Bernard      1
       Leander Dendoncker      1
                 Dan Burn      1
             Karlan Grant      1
               Joel Matip      1
             Adam Lallana      1
          Héctor Bellerín      1
           Mohamed Elneny      1
               Alex Iwobi      1
               Scott Dann      1
         Cheikhou Kouyaté      1
               Liam Delap      0
              Caleb Watts      0
          Tyrese Francois      0
         Filip Krovinovic      0
         Lewis Richardson      0
            Rhys Williams      0
           Robert Sánchez      0
        Antwoine Hackford      0
             Matthew Cash      0
    Konstantinos Tsimikas      0
                  Vitinha      0
             Kyle Edwards      0
          Romaine Sawyers      0
         Dara O&#039;Shea      0
        Ian Poveda-Ocampo      0
         Jamie Shackleton      0
            Dane Scarlett      0
          Vladimir Coufal      0
             Jacob Ramsey      0
         Antonee Robinson      0
               Leif Davis      0
                 Max Lowe      0
            Niall Huggins      0
            Theo Corbeanu      0
           Conor Townsend      0
          Aaron Cresswell      0
               Mark Noble      0
            James Tomkins      0
                   Adrián      0
             Martin Kelly      0
                Joel Ward      0
           Calum Chambers      0
             James Milner      0
            Mamadou Sakho      0
              Luke Ayling      0
            Illan Meslier      0
              Marek Rodák      0
            Joel Mumbongo      0
      Alexandre Jankewitz      0
              Jake Vokins      0
          Elliot Anderson      0
             Divock Origi      0
              Joshua King      0
             Matt Ritchie      0
           Sead Kolasinac      0
      Andreas Christensen      0
               Bernd Leno      0
                Eric Dier      0
              Hugo Lloris      0
            Alex McCarthy      0
           James McArthur      0
          Willy Caballero      0
              Fernandinho      0
          Nathaniel Clyne      0
           James McCarthy      0
            Phil Jagielka      0
           Seamus Coleman      0
             Odion Ighalo      0
                Juan Mata      0
      Timothy Fosu-Mensah      0
             David de Gea      0
             Kieran Gibbs      0
          Darren Randolph      0
          Christian Fuchs      0
               Wes Morgan      0
        Kasper Schmeichel      0
          Jordan Pickford      0
      Patrick van Aanholt      0
           DeAndre Yedlin      0
                Jack Cork      0
              Neil Taylor      0
       Federico Fernández      0
         Lukasz Fabianski      0
            Fikayo Tomori      0
            Nemanja Matic      0
       Branislav Ivanovic      0
              Josh Onomah      0
               Ben Davies      0
                Dele Alli      0
             Erik Pieters      0
       Kyle Walker-Peters      0
             Matt Targett      0
             Fabian Delph      0
            Phil Bardsley      0
             Jack Butland      0
           Charlie Austin      0
            Cédric Soares      0
               Shane Long      0
            Ryan Bertrand      0
           Fraser Forster      0
               John Ruddy      0
              Karl Darlow      0
           Moussa Sissoko      0
             Demarai Gray      0
        N&#039;Golo Kanté      0
         Ahmed Elmohamady      0
              Ryan Fraser      0
            Islam Slimani      0
                    Allan      0
               Moise Kean      0
                  Emerson      0
          Felipe Anderson      0
             Jonjoe Kenny      0
               Tom Davies      0
                Sam Field      0
             Joseph Gomez      0
            Sam Johnstone      0
              Harry Winks      0
            Axel Tuanzebe      0
            Harrison Reed      0
          Xherdan Shaqiri      0
           Vicente Guaita      0
          Pablo Hernández      0
              Alex Telles      0
              Lucas Digne      0
           Nampalys Mendy      0
           Arthur Masuaku      0
   Ainsley Maitland-Niles      0
              Rob Holding      0
              Lys Mousset      0
               Kevin Long      0
              Eric Bailly      0
            Jack Stephens      0
         Javier Manquillo      0
         Shkodran Mustafi      0
         Robert Snodgrass      0
           Jake Livermore      0
             Ahmed Hegazy      0
            Morgan Sanson      0
                  Fabinho      0
       Maxime Le Marchand      0
          Ricardo Pereira      0
           Kamil Grosicki      0
      Oleksandr Zinchenko      0
          Aymeric Laporte      0
            Dani Ceballos      0
                 Mat Ryan      0
              André Gomes      0
            Thomas Partey      0
          Alphonse Areola      0
                    Jonny      0
             Kiko Casilla      0
            Mateo Kovacic      0
           Charlie Taylor      0
               Kenny Tete      0
          Fernando Marçal      0
           Aaron Ramsdale      0
         Tosin Adarabioyo      0
           Rhian Brewster      0
            Rekeem Harper      0
                Nick Pope      0
           Michael Hector      0
               Naby Keita      0
                 Bernardo      0
                     Kepa      0
          Patrick Cutrone      0
         Aboubakar Kamara      0
     Jean-Philippe Gbamin      0
        Emiliano Martinez      0
          Hamza Choudhury      0
                Joe Rodon      0
             Ethan Ampadu      0
           Jayson Molumby      0
        Andriy Yarmolenko      0
               Robin Koch      0
         Davinson Sánchez      0
           José Izquierdo      0
            Nélson Semedo      0
             Cengiz Ünder      0
             Douglas Luiz      0
          Terence Kongolo      0
             Isaac Hayden      0
                  Ederson      0
            Dale Stephens      0
             Davy Pröpper      0
          Mohammed Salisu      0
            Edouard Mendy      0
     Rúnar Alex Rúnarsson      0
            Rúben Vinagre      0
             Matt Doherty      0
             Rui Patrício      0
             David Button      0
      Alireza Jahanbakhsh      0
          Neeskens Kebano      0
              Lee Peltier      0
          Ibrahima Diallo      0
          Martin Dubravka      0
          Michael Obafemi      0
             Reiss Nelson      0
               Cenk Tosun      0
             Franck Zambo      0
              Jamal Lewis      0
              Ben Godfrey      0
            Wesley Fofana      0
              Will Norris      0
              Josh Benson      0
               Ozan Kabak      0
               Max Kilman      0
             Kayne Ramsay      0
                Ben White      0
               Yan Valery      0
          Sergio Reguilón      0
                 Tim Ream      0
           Sean Longstaff      0
               Denis Odoi      0
              Robin Olsen      0
             Okay Yokuslu      0
        Marvelous Nakamba      0
        Matthew Longstaff      0
            Billy Gilmour      0
    Daniel N&#039;Lundulu      0
        Caoimhin Kelleher      0
             Zack Steffen      0
                   Wesley      0
           Oliver Norwood      0
               John Fleck      0
           John Lundstram      0
             Enda Stevens      0
           George Baldock      0
      Jack O&#039;Connell      0
             Chris Basham      0
                John Egan      0
           Dean Henderson      0
               Pablo Marí      0
            João Virgínia      0
           Ki-Jana Hoever      0
           Josh Brownhill      0
            Jack Robinson      0
               Oskar Buur      0
        William Smallbone      0
          Japhet Tanganga      0
            Neco Williams      0
            Owen Otasowie      0
             Scott Carson      0
           Anthony Gordon      0
       Amad Diallo Traore      0
           Niels Nkounkou      0
         Brandon Williams      0
              Eric Garcia      0
              Andi Zeqiri      0
              Femi Seriki      0
           Anthony Elanga      0
          Gaetano Berardi      0
   Jaden Philogene-Bidace      0
         Nathan Broadhead      0
           Sidnei Tavares      0
          Shola Shoretire      0
       Carney Chukwuemeka      0
   Bailey Peacock-Farrell      0
              Reda Khadra      0
       Thakgalo Leshabela      0
            Iliman Ndiaye      0
              Jakub Moder      0
         Allan Tchaptchet      0
                Percy Tau      0

### 6.Tampilkan dataframe yang hanya terdiri dari nama pemain, goal, posisi, nama klub pemain, dan jumlah kartu kuning

In [ ]:
import pandas as pd

# Membaca file CSV (pastikan file sudah diupload ke Google Colab)
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Memilih dan mengatur urutan kolom
result_df = df[['player_name', 'goals', 'position', 'team_title', 'yellow_cards']]

# Menampilkan dataframe dengan gaya agar lebih mudah dibaca
from IPython.display import display
display(result_df)

,player_name,goals,position,team_title,yellow_cards
0,Harry Kane,23,F,Tottenham,1
1,Mohamed Salah,22,F M S,Liverpool,0
2,Bruno Fernandes,18,M S,Manchester United,6
3,Son Heung-Min,17,F M S,Tottenham,0
4,Patrick Bamford,17,F S,Leeds,3
5,Dominic Calvert-Lewin,16,F S,Everton,3
6,Jamie Vardy,15,F S,Leicester,1
7,Ollie Watkins,14,F,Aston Villa,2
8,Ilkay Gündogan,13,M S,Manchester City,1
9,Alexandre Lacazette,13,F M S,Arsenal,3
10,Callum Wilson,12,F S,Newcastle United,2
11,Kelechi Iheanacho,12,F S,Leicester,1
12,Danny Ings,12,F S,Southampton,1
13,Chris Wood,12,F S,Burnley,0
14,Wilfried Zaha,11,F M S,Crystal Palace,6
15,Marcus Rashford,11,F M S,Manchester United,4
16,Sadio Mané,11,F M S,Liverpool,3
17,Gareth Bale,11,M S,Tottenham,1
18,Matheus Pereira,11,M S,West Bromwich Albion,2
19,Pierre-Emerick Aubameyang,10,F M S,Arsenal,2
20,Michail Antonio,10,F S,West Ham,3
21,Christian Benteke,10,F S,Crystal Palace,1
22,Raheem Sterling,10,F M S,Manchester City,3
23,Edinson Cavani,10,F S,Manchester United,4
24,Anwar El Ghazi,10,F M S,Aston Villa,2
25,Tomas Soucek,10,M,West Ham,7
26,Roberto Firmino,9,F M S,Liverpool,2
27,Jesse Lingard,9,F M,West Ham,3
28,Riyad Mahrez,9,F M S,Manchester City,0
29,Harvey Barnes,9,F M S,Leicester,0
30,Diogo Jota,9,F M S,Liverpool,2
31,Che Adams,9,F S,Southampton,1
32,James Ward-Prowse,8,D M,Southampton,5
33,Jarrod Bowen,8,F M S,West Ham,0
34,Neal Maupay,8,F M S,Brighton,1
35,Gabriel Jesus,8,F M S,Manchester City,2
36,Nicolas Pepe,8,F M S,Arsenal,1
37,Phil Foden,8,F M S,Manchester City,0
38,Joe Willock,8,M S,"Arsenal,Newcastle United",1
39,James Maddison,8,M S,Leicester,4
40,Stuart Dallas,8,D M,Leeds,7
41,Jack Harrison,8,M S,Leeds,2
42,Bertrand Traoré,7,F M S,Aston Villa,1
43,Jorginho,7,M S,Chelsea,2
44,Rodrigo,7,F M S,Leeds,3
45,Richarlison,7,F M S,Everton,3
46,Ferrán Torres,7,F M S,Manchester City,1
47,Mason Greenwood,7,F M S,Manchester United,2
48,David McGoldrick,7,F M S,Sheffield United,7
49,Timo Werner,6,F M S,Chelsea,2
50,Danny Welbeck,6,F M S,Brighton,0
51,Jack Grealish,6,F M S,Aston Villa,5
52,Tammy Abraham,6,F S,Chelsea,0
53,Gylfi Sigurdsson,6,F M S,Everton,2
54,James Rodríguez,6,F M S,Everton,4
55,Youri Tielemans,6,M S,Leicester,6
56,Mason Mount,6,F M S,Chelsea,2
57,Raphinha,6,M S,Leeds,3
58,Kevin De Bruyne,5,M S,Manchester City,1
59,Kurt Zouma,5,D S,Chelsea,3
60,Callum Robinson,5,F M S,West Bromwich Albion,0
61,Lewis Dunk,5,D,Brighton,5
62,Pedro Neto,5,F M S,Wolverhampton Wanderers,4
63,Bobby Reid,5,D F M S,Fulham,7
64,Rúben Neves,5,M S,Wolverhampton Wanderers,7
65,Bukayo Saka,5,D F M S,Arsenal,1
66,Leandro Trossard,5,F M S,Brighton,2
67,Joelinton,4,F M S,Newcastle United,3
68,Olivier Giroud,4,F S,Chelsea,1
69,Anthony Martial,4,F M S,Manchester United,0
70,John Stones,4,D,Manchester City,0
71,Christian Pulisic,4,F M S,Chelsea,2
72,Raúl Jiménez,4,F,Wolverhampton Wanderers,0
73,Mateusz Klich,4,M S,Leeds,6
74,Kai Havertz,4,F M S,Chelsea,2
75,Ademola Lookman,4,F M S,Fulham,5
76,Scott McTominay,4,M S,Manchester United,3
77,Stuart Armstrong,4,M S,Southampton,3
78,Miguel Almirón,4,F M S,Newcastle United,3
79,Eberechi Eze,4,M S,Crystal Palace,3
80,Fabio Silva,4,F S,Wolverhampton Wanderers,2
81,Allan Saint-Maximin,3,F M S,Newcastle United,0
82,Jannik Vestergaard,3,D S,Southampton,3
83,Pascal Groß,3,D M S,Brighton,3
84,Theo Walcott,3,F M S,"Everton,Southampton",0
85,Angelo Ogbonna,3,D,West Ham,5
86,Ross Barkley,3,M S,"Aston Villa,Chelsea",0
87,Ashley Westwood,3,M,Burnley,7
88,Aleksandar Mitrovic,3,F S,Fulham,3
89,Ben Chilwell,3,D M,Chelsea,3
90,Craig Dawson,3,D,West Ham,3
91,Kyle Bartley,3,D S,West Bromwich Albion,4
92,Matej Vydra,3,F S,Burnley,0
93,Michael Keane,3,D S,Everton,4
94,Paul Pogba,3,M S,Manchester United,3
95,Pablo Fornals,3,F M S,West Ham,3
96,Lucas Moura,3,F M S,Tottenham,1
97,Hélder Costa,3,M S,Leeds,0
98,Romain Saiss,3,D,Wolverhampton Wanderers,2
99,Ivan Cavaleiro,3,D F M S,Fulham,2
100,Ashley Barnes,3,F M S,Burnley,4
101,Josh Maja,3,F S,Fulham,0
102,Daniel James,3,M S,Manchester United,3
103,Tanguy NDombele Alvaro,3,M S,Tottenham,3
104,Sébastien Haller,3,F S,West Ham,0
105,Billy Sharp,3,F S,Sheffield United,1
106,John McGinn,3,M,Aston Villa,12
107,Takumi Minamino,3,F M S,"Liverpool,Southampton",1
108,Daniel Podence,3,F M S,Wolverhampton Wanderers,3
109,Mbaye Diagne,3,F S,West Bromwich Albion,2
110,Pierre-Emile Højbjerg,2,M,Tottenham,9
111,Sergio Agüero,2,F M S,Manchester City,0
112,Ola Aina,2,D M,Fulham,3
113,Jeffrey Schlupp,2,M S,Crystal Palace,3
114,Jamaal Lascelles,2,D,Newcastle United,4
115,Ayoze Pérez,2,F M S,Leicester,2
116,Georginio Wijnaldum,2,M S,Liverpool,1
117,Nathan Redmond,2,F M S,Southampton,1
118,Jonny Evans,2,D,Leicester,7
119,Adama Traoré,2,D F M S,Wolverhampton Wanderers,4
120,Tyrone Mings,2,D,Aston Villa,4
121,Marcos Alonso,2,D S,Chelsea,2
122,Ben Mee,2,D,Burnley,3
123,Johann Berg Gudmundsson,2,M S,Burnley,2
124,Michy Batshuayi,2,F S,Crystal Palace,0
125,Harry Maguire,2,D,Manchester United,11
126,Abdoulaye Doucouré,2,M,Everton,6
127,Matt Phillips,2,M S,West Bromwich Albion,1
128,Hal Robson-Kanu,2,F S,West Bromwich Albion,2
129,Jeff Hendrick,2,M S,Newcastle United,1
130,Trent Alexander-Arnold,2,D S,Liverpool,2
131,João Cancelo,2,D M S,Manchester City,5
132,Rodri,2,M S,Manchester City,6
133,Issa Diop,2,D S,West Ham,3
134,Thiago Silva,2,D,Chelsea,3
135,Benjamin Mendy,2,D M S,Manchester City,2
136,Serge Aurier,2,D M,Tottenham,0
137,Bernardo Silva,2,F M S,Manchester City,5
138,Semi Ajayi,2,D S,West Bromwich Albion,3
139,Aaron Wan-Bissaka,2,D,Manchester United,3
140,Gabriel,2,D S,Arsenal,2
141,Jairo Riedewald,2,M S,Crystal Palace,4
142,Solly March,2,D M S,Brighton,0
143,Jacob Murphy,2,D M S,Newcastle United,3
144,Timothy Castagne,2,D M,Leicester,1
145,Callum Hudson-Odoi,2,D F M S,Chelsea,0
146,Eddie Nketiah,2,F S,Arsenal,0
147,Yerry Mina,2,D S,Everton,2
148,Dwight McNeil,2,M S,Burnley,1
149,Emile Smith-Rowe,2,M S,Arsenal,0
150,Trézéguet,2,F M S,Aston Villa,0
151,Ezri Konsa Ngoyo,2,D S,Aston Villa,3
152,Gabriel Martinelli,2,F M S,Arsenal,0
153,James Justin,2,D,Leicester,4
154,Aaron Connolly,2,F M S,Brighton,0
155,Ezgjan Alioski,2,D M S,Leeds,7
156,Hakim Ziyech,2,F M S,Chelsea,3
157,Conor Gallagher,2,M S,West Bromwich Albion,11
158,Jayden Bogle,2,D M S,Sheffield United,2
159,Fabian Schär,1,D S,Newcastle United,4
160,Granit Xhaka,1,D M S,Arsenal,7
161,Thiago Alcántara,1,M S,Liverpool,4
162,Joel Matip,1,D S,Liverpool,2
163,Adam Lallana,1,F M S,Brighton,0
164,Héctor Bellerín,1,D S,Arsenal,8
165,Mohamed Elneny,1,M S,Arsenal,3
166,Alex Iwobi,1,D F M S,Everton,0
167,Scott Dann,1,D,Crystal Palace,1
168,Cheikhou Kouyaté,1,D M S,Crystal Palace,4
169,Manuel Lanzini,1,M S,West Ham,1
170,Andy Carroll,1,F S,Newcastle United,1
171,Nathan Aké,1,D S,Manchester City,4
172,Jordan Henderson,1,D M S,Liverpool,0
173,Kyle Walker,1,D S,Manchester City,1
174,Toby Alderweireld,1,D,Tottenham,2
175,Erik Lamela,1,F M S,Tottenham,4
176,Jordan Ayew,1,F M S,Crystal Palace,4
177,César Azpilicueta,1,D S,Chelsea,5
178,Ruben Loftus-Cheek,1,F M S,"Chelsea,Fulham",3
179,Gary Cahill,1,D,Crystal Palace,3
180,Willian,1,F M S,Arsenal,0
181,Dwight Gayle,1,F S,Newcastle United,0
182,Marc Albrighton,1,D M S,Leicester,2
183,Daniel Amartey,1,D S,Leicester,2
184,Jonjo Shelvey,1,M S,Newcastle United,7
185,Andros Townsend,1,F M S,Crystal Palace,0
186,Robbie Brady,1,M S,Burnley,3
187,Virgil van Dijk,1,D,Liverpool,1
188,Oriol Romeu,1,M,Southampton,6
189,Jay Rodriguez,1,F M S,Burnley,3
190,Paul Dummett,1,D S,Newcastle United,2
191,Ciaran Clark,1,D S,Newcastle United,3
192,Alex Oxlade-Chamberlain,1,F M S,Liverpool,0
193,Mason Holgate,1,D M S,Everton,8
194,Luke Shaw,1,D S,Manchester United,8
195,Tyler Roberts,1,F M S,Leeds,3
196,Keinan Davis,1,F S,Aston Villa,0
197,Dennis Praet,1,M S,Leicester,0
198,Alisson,1,GK,Liverpool,1
199,Mario Lemina,1,D M S,Fulham,5
200,Emil Krafth,1,D S,Newcastle United,4
201,Matthew Lowton,1,D,Burnley,5
202,James Tarkowski,1,D,Burnley,6
203,David Luiz,1,D S,Arsenal,1
204,Andrew Robertson,1,D,Liverpool,2
205,Oliver McBurnie,1,F S,Sheffield United,2
206,Antonio Rüdiger,1,D,Chelsea,0
207,Diego Llorente,1,D S,Leeds,1
208,Willian José,1,F S,Wolverhampton Wanderers,0
209,Martin Odegaard,1,M S,Arsenal,0
210,João Moutinho,1,M S,Wolverhampton Wanderers,3
211,Said Benrahma,1,M S,West Ham,0
212,Darnell Furlong,1,D M S,West Bromwich Albion,5
213,Oliver Burke,1,F S,Sheffield United,2
214,Caglar Söyüncü,1,D S,Leicester,2
215,Wilfred Ndidi,1,D M S,Leicester,6
216,Luka Milivojevic,1,M S,Crystal Palace,8
217,Declan Rice,1,M,West Ham,2
218,Yves Bissouma,1,M S,Brighton,8
219,Giovani Lo Celso,1,M S,Tottenham,5
220,Jean-Philippe Mateta,1,F S,Crystal Palace,0
221,Jan Bednarek,1,D,Southampton,4
222,Victor Lindelöf,1,D,Manchester United,0
223,Joachim Andersen,1,D S,Fulham,7
224,Ben Johnson,1,D M S,West Ham,1
225,Grady Diangana,1,F M S,West Bromwich Albion,0
226,Curtis Jones,1,M S,Liverpool,2
227,Rayan Ait Nouri,1,D M S,Wolverhampton Wanderers,0
228,Fred,1,M S,Manchester United,5
229,Joe Bryan,1,D M S,Fulham,2
230,Tom Cairney,1,M S,Fulham,2
231,Willy Boly,1,D,Wolverhampton Wanderers,1
232,Conor Coady,1,D,Wolverhampton Wanderers,5
233,Morgan Gibbs-White,1,F M S,Wolverhampton Wanderers,0
234,Kortney Hause,1,D,Aston Villa,2
235,Ryan Fredericks,1,D M S,West Ham,2
236,Fabián Balbuena,1,D S,West Ham,1
237,Bernard,1,F M S,Everton,2
238,Leander Dendoncker,1,D M S,Wolverhampton Wanderers,3
239,Dan Burn,1,D M S,Brighton,5
240,Karlan Grant,1,F M S,West Bromwich Albion,1
241,Carlos Vinicius,1,F S,Tottenham,2
242,Adam Webster,1,D,Brighton,4
243,Moussa Djenepo,1,M S,Southampton,5
244,Ben Osborn,1,D F M S,Sheffield United,1
245,Conor Hourihane,1,M S,Aston Villa,0
246,Steven Alzate,1,D M S,Brighton,2
247,Reece James,1,D M S,Chelsea,3
248,Kieran Tierney,1,D S,Arsenal,4
249,Tyrick Mitchell,1,D,Crystal Palace,1
250,Tariq Lamptey,1,D M,Brighton,2
251,Nathaniel Phillips,1,D S,Liverpool,2
252,Sander Berge,1,M S,Sheffield United,4
253,Steven Bergwijn,1,F M S,Tottenham,3
254,Alexis Mac Allister,1,F M S,Brighton,1
255,Nathan Tella,1,F M S,Southampton,2
256,Jimmy Dunne,1,D,Burnley,0
257,Luke Thomas,1,D M S,Leicester,2
258,Pascal Struijk,1,D M S,Leeds,3
259,Kalvin Phillips,1,M S,Leeds,10
260,Joël Veltman,1,D M S,Brighton,3
261,Liam Cooper,1,D,Leeds,4
262,Donny van de Beek,1,M S,Manchester United,1
263,Rúben Dias,1,D,Manchester City,3
264,Kean Bryan,1,D S,Sheffield United,1
265,Fabio Carvalho,1,F M S,Fulham,0
266,Daniel Jebbison,1,F S,Sheffield United,0
267,Bernd Leno,0,GK,Arsenal,0
268,Andreas Christensen,0,D S,Chelsea,2
269,Sead Kolasinac,0,D,Arsenal,0
270,Matt Ritchie,0,D M S,Newcastle United,2
271,Joshua King,0,S,Everton,0
272,Divock Origi,0,F S,Liverpool,0
273,Mamadou Sakho,0,D S,Crystal Palace,0
274,James Milner,0,D M S,Liverpool,3
275,Calum Chambers,0,D S,Arsenal,0
276,Joel Ward,0,D S,Crystal Palace,5
277,Martin Kelly,0,S,Crystal Palace,0
278,Adrián,0,GK,Liverpool,0
279,James Tomkins,0,D S,Crystal Palace,1
280,Mark Noble,0,M S,West Ham,1
281,Aaron Cresswell,0,D,West Ham,3
282,Darren Randolph,0,GK,West Ham,0
283,Kieran Gibbs,0,D S,West Bromwich Albion,0
284,David de Gea,0,GK,Manchester United,0
285,Timothy Fosu-Mensah,0,D,Manchester United,1
286,Juan Mata,0,M S,Manchester United,0
287,Odion Ighalo,0,S,Manchester United,0
288,Seamus Coleman,0,D M S,Everton,0
289,Phil Jagielka,0,D S,Sheffield United,1
290,James McCarthy,0,M S,Crystal Palace,1
291,Nathaniel Clyne,0,D,Crystal Palace,2
292,Fernandinho,0,M S,Manchester City,6
293,Willy Caballero,0,GK,Chelsea,0
294,James McArthur,0,M S,Crystal Palace,3
295,Alex McCarthy,0,GK,Southampton,2
296,Hugo Lloris,0,GK,Tottenham,0
297,Eric Dier,0,D,Tottenham,3
298,Dele Alli,0,M S,Tottenham,0
299,Ben Davies,0,D S,Tottenham,1
300,Josh Onomah,0,M S,Fulham,1
301,Branislav Ivanovic,0,D S,West Bromwich Albion,2
302,Nemanja Matic,0,M S,Manchester United,2
303,Fikayo Tomori,0,S,Chelsea,0
304,Lukasz Fabianski,0,GK,West Ham,2
305,Federico Fernández,0,D,Newcastle United,4
306,Neil Taylor,0,S,Aston Villa,1
307,Jack Cork,0,M S,Burnley,2
308,DeAndre Yedlin,0,D S,Newcastle United,0
309,Patrick van Aanholt,0,D M S,Crystal Palace,2
310,Jordan Pickford,0,GK,Everton,1
311,Kasper Schmeichel,0,GK,Leicester,0
312,Wes Morgan,0,S,Leicester,0
313,Christian Fuchs,0,D S,Leicester,4
314,N&#039;Golo Kanté,0,M S,Chelsea,7
315,Demarai Gray,0,S,Leicester,0
316,Moussa Sissoko,0,D M S,Tottenham,3
317,Karl Darlow,0,GK,Newcastle United,2
318,John Ruddy,0,GK S,Wolverhampton Wanderers,0
319,Fraser Forster,0,GK,Southampton,0
320,Ryan Bertrand,0,D,Southampton,5
321,Shane Long,0,F S,Southampton,0
322,Cédric Soares,0,D S,Arsenal,1
323,Charlie Austin,0,S,West Bromwich Albion,0
324,Jack Butland,0,GK,Crystal Palace,0
325,Phil Bardsley,0,D S,Burnley,2
326,Fabian Delph,0,D M S,Everton,1
327,Matt Targett,0,D,Aston Villa,7
328,Kyle Walker-Peters,0,D,Southampton,4
329,Erik Pieters,0,D M S,Burnley,1
330,Xherdan Shaqiri,0,F M S,Liverpool,2
331,Harrison Reed,0,M S,Fulham,5
332,Axel Tuanzebe,0,D S,Manchester United,2
333,Harry Winks,0,M S,Tottenham,5
334,Sam Johnstone,0,GK,West Bromwich Albion,1
335,Joseph Gomez,0,D S,Liverpool,0
336,Sam Field,0,S,West Bromwich Albion,0
337,Tom Davies,0,D M S,Everton,3
338,Jonjoe Kenny,0,D S,Everton,0
339,Felipe Anderson,0,S,West Ham,0
340,Emerson,0,S,Chelsea,0
341,Moise Kean,0,S,Everton,0
342,Allan,0,M S,Everton,6
343,Islam Slimani,0,S,Leicester,0
344,Ryan Fraser,0,F M S,Newcastle United,0
345,Ahmed Elmohamady,0,D S,Aston Villa,2
346,Jake Livermore,0,M S,West Bromwich Albion,2
347,Robert Snodgrass,0,M S,"West Bromwich Albion,West Ham",2
348,Shkodran Mustafi,0,S,Arsenal,0
349,Javier Manquillo,0,D S,Newcastle United,1
350,Jack Stephens,0,D M S,Southampton,2
351,Eric Bailly,0,D S,Manchester United,3
352,Kevin Long,0,D S,Burnley,2
353,Lys Mousset,0,F S,Sheffield United,0
354,Rob Holding,0,D S,Arsenal,2
355,Ainsley Maitland-Niles,0,D M S,"Arsenal,West Bromwich Albion",2
356,Arthur Masuaku,0,D M,West Ham,2
357,Nampalys Mendy,0,M S,Leicester,5
358,Lucas Digne,0,D M,Everton,2
359,Alex Telles,0,D S,Manchester United,0
360,Pablo Hernández,0,M S,Leeds,1
361,Vicente Guaita,0,GK,Crystal Palace,2
362,Mateo Kovacic,0,M S,Chelsea,4
363,Kiko Casilla,0,GK,Leeds,0
364,Jonny,0,D,Wolverhampton Wanderers,0
365,Alphonse Areola,0,GK,Fulham,2
366,Thomas Partey,0,M S,Arsenal,5
367,André Gomes,0,M S,Everton,3
368,Mat Ryan,0,GK,"Arsenal,Brighton",1
369,Dani Ceballos,0,M S,Arsenal,4
370,Aymeric Laporte,0,D S,Manchester City,1
371,Oleksandr Zinchenko,0,D M S,Manchester City,0
372,Kamil Grosicki,0,M S,West Bromwich Albion,0
373,Ricardo Pereira,0,D M S,Leicester,3
374,Maxime Le Marchand,0,D S,Fulham,2
375,Fabinho,0,D M S,Liverpool,6
376,Morgan Sanson,0,M S,Aston Villa,3
377,Ahmed Hegazy,0,D,West Bromwich Albion,0
378,Emiliano Martinez,0,GK,Aston Villa,1
379,Jean-Philippe Gbamin,0,S,Everton,0
380,Aboubakar Kamara,0,F M S,Fulham,1
381,Patrick Cutrone,0,S,Wolverhampton Wanderers,0
382,Kepa,0,GK S,Chelsea,1
383,Bernardo,0,D M S,Brighton,0
384,Naby Keita,0,M S,Liverpool,1
385,Michael Hector,0,D S,Fulham,2
386,Nick Pope,0,GK,Burnley,1
387,Rekeem Harper,0,S,West Bromwich Albion,0
388,Rhian Brewster,0,F M S,Sheffield United,1
389,Tosin Adarabioyo,0,D,Fulham,1
390,Aaron Ramsdale,0,GK,Sheffield United,1
391,Fernando Marçal,0,D M S,Wolverhampton Wanderers,2
392,Kenny Tete,0,D S,Fulham,3
393,Charlie Taylor,0,D S,Burnley,1
394,Davy Pröpper,0,M S,Brighton,0
395,Dale Stephens,0,M S,Burnley,1
396,Ederson,0,GK,Manchester City,3
397,Isaac Hayden,0,D M S,Newcastle United,8
398,Terence Kongolo,0,D,Fulham,0
399,Douglas Luiz,0,M S,Aston Villa,8
400,Cengiz Ünder,0,M S,Leicester,0
401,Nélson Semedo,0,D M,Wolverhampton Wanderers,5
402,José Izquierdo,0,S,Brighton,0
403,Davinson Sánchez,0,D S,Tottenham,1
404,Robin Koch,0,D M S,Leeds,1
405,Andriy Yarmolenko,0,M S,West Ham,3
406,Jayson Molumby,0,S,Brighton,0
407,Ethan Ampadu,0,D M S,Sheffield United,3
408,Joe Rodon,0,D S,Tottenham,0
409,Hamza Choudhury,0,M S,Leicester,1
410,Franck Zambo,0,M S,Fulham,6
411,Cenk Tosun,0,S,Everton,2
412,Reiss Nelson,0,S,Arsenal,0
413,Michael Obafemi,0,S,Southampton,0
414,Martin Dubravka,0,GK,Newcastle United,0
415,Ibrahima Diallo,0,M S,Southampton,2
416,Lee Peltier,0,D S,West Bromwich Albion,1
417,Neeskens Kebano,0,M S,Fulham,0
418,Alireza Jahanbakhsh,0,D F M S,Brighton,3
419,David Button,0,GK,West Bromwich Albion,0
420,Rui Patrício,0,GK,Wolverhampton Wanderers,1
421,Matt Doherty,0,D M S,Tottenham,2
422,Rúben Vinagre,0,D S,Wolverhampton Wanderers,0
423,Rúnar Alex Rúnarsson,0,S,Arsenal,0
424,Edouard Mendy,0,GK,Chelsea,2
425,Mohammed Salisu,0,D S,Southampton,0
426,Okay Yokuslu,0,M S,West Bromwich Albion,4
427,Robin Olsen,0,GK,Everton,1
428,Denis Odoi,0,D,Fulham,1
429,Sean Longstaff,0,M S,Newcastle United,2
430,Tim Ream,0,D,Fulham,0
431,Sergio Reguilón,0,D M S,Tottenham,5
432,Yan Valery,0,D S,Southampton,0
433,Ben White,0,D M,Brighton,3
434,Kayne Ramsay,0,D,Southampton,1
435,Max Kilman,0,D S,Wolverhampton Wanderers,4
436,Ozan Kabak,0,D,Liverpool,3
437,Josh Benson,0,M S,Burnley,0
438,Will Norris,0,GK,Burnley,0
439,Wesley Fofana,0,D S,Leicester,7
440,Ben Godfrey,0,D S,Everton,4
441,Jamal Lewis,0,D S,Newcastle United,4
442,Dean Henderson,0,GK S,Manchester United,2
443,John Egan,0,D S,Sheffield United,7
444,Chris Basham,0,D M,Sheffield United,4
445,Jack O&#039;Connell,0,D,Sheffield United,0
446,George Baldock,0,D,Sheffield United,6
447,Enda Stevens,0,D M,Sheffield United,6
448,John Lundstram,0,M S,Sheffield United,8
449,John Fleck,0,M S,Sheffield United,3
450,Oliver Norwood,0,M S,Sheffield United,6
451,Wesley,0,S,Aston Villa,0
452,Zack Steffen,0,GK,Manchester City,0
453,Caoimhin Kelleher,0,GK,Liverpool,0
454,Daniel N&#039;Lundulu,0,S,Southampton,0
455,Billy Gilmour,0,M S,Chelsea,0
456,Matthew Longstaff,0,M S,Newcastle United,0
457,Marvelous Nakamba,0,M S,Aston Villa,3
458,Eric Garcia,0,D S,Manchester City,0
459,Brandon Williams,0,D S,Manchester United,0
460,Niels Nkounkou,0,D,Everton,1
461,Amad Diallo Traore,0,M S,Manchester United,0
462,Anthony Gordon,0,M S,Everton,0
463,Scott Carson,0,GK,Manchester City,0
464,Owen Otasowie,0,M S,Wolverhampton Wanderers,1
465,Neco Williams,0,D S,Liverpool,1
466,Japhet Tanganga,0,D,Tottenham,2
467,William Smallbone,0,M S,Southampton,0
468,Oskar Buur,0,S,Wolverhampton Wanderers,0
469,Jack Robinson,0,D S,Sheffield United,3
470,Josh Brownhill,0,M S,Burnley,2
471,Ki-Jana Hoever,0,D S,Wolverhampton Wanderers,1
472,João Virgínia,0,S,Everton,0
473,Pablo Marí,0,D,Arsenal,2
474,Bailey Peacock-Farrell,0,GK,Burnley,0
475,Jake Vokins,0,D,Southampton,0
476,Alexandre Jankewitz,0,M S,Southampton,0
477,Joel Mumbongo,0,S,Burnley,1
478,Marek Rodák,0,GK,Fulham,0
479,Illan Meslier,0,GK,Leeds,0
480,Luke Ayling,0,D M,Leeds,7
481,Jamie Shackleton,0,D M S,Leeds,0
482,Ian Poveda-Ocampo,0,S,Leeds,0
483,Dara O&#039;Shea,0,D S,West Bromwich Albion,3
484,Romaine Sawyers,0,M S,West Bromwich Albion,3
485,Kyle Edwards,0,M S,West Bromwich Albion,0
486,Vitinha,0,M S,Wolverhampton Wanderers,0
487,Konstantinos Tsimikas,0,S,Liverpool,0
488,Matthew Cash,0,D,Aston Villa,6
489,Liam Delap,0,S,Manchester City,0
490,Conor Townsend,0,D M,West Bromwich Albion,0
491,Max Lowe,0,D S,Sheffield United,1
492,Leif Davis,0,S,Leeds,0
493,Antonee Robinson,0,D M S,Fulham,4
494,Jacob Ramsey,0,M S,Aston Villa,0
495,Vladimir Coufal,0,D M,West Ham,3
496,Filip Krovinovic,0,M S,West Bromwich Albion,0
497,Lewis Richardson,0,S,Burnley,0
498,Rhys Williams,0,D S,Liverpool,0
499,Robert Sánchez,0,GK,Brighton,2
500,Andi Zeqiri,0,S,Brighton,0
501,Elliot Anderson,0,S,Newcastle United,0
502,Theo Corbeanu,0,S,Wolverhampton Wanderers,0
503,Niall Huggins,0,S,Leeds,0
504,Antwoine Hackford,0,S,Sheffield United,0
505,Percy Tau,0,M S,Brighton,0
506,Reda Khadra,0,S,Brighton,0
507,Caleb Watts,0,S,Southampton,1
508,Allan Tchaptchet,0,S,Southampton,0
509,Jakub Moder,0,D M S,Brighton,0
510,Iliman Ndiaye,0,S,Sheffield United,0
511,Thakgalo Leshabela,0,S,Leicester,0
512,Dane Scarlett,0,S,Tottenham,0
513,Carney Chukwuemeka,0,S,Aston Villa,0
514,Shola Shoretire,0,S,Manchester United,0
515,Sidnei Tavares,0,M S,Leicester,0
516,Nathan Broadhead,0,S,Everton,0

### 7.Tampilkan semua pemain dari klub “Liverpool”

In [ ]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Filter pemain dari Liverpool
liverpool_players = df[df['team_title'] == 'Liverpool']

# Menampilkan kolom yang diinginkan (nama pemain dan informasi tambahan)
result = liverpool_players[['player_name', 'position', 'games', 'goals', 'assists']]

# Mengurutkan berdasarkan nama pemain
result_sorted = result.sort_values(by='player_name')

# Menampilkan hasil
print("Daftar Pemain Liverpool:")
print(result_sorted.to_string(index=False))

Daftar Pemain Liverpool:
            player_name position  games  goals  assists
                 Adrián       GK      3      0        0
Alex Oxlade-Chamberlain    F M S     13      1        1
                Alisson       GK     33      1        0
       Andrew Robertson        D     38      1        7
      Caoimhin Kelleher       GK      2      0        0
           Curtis Jones      M S     24      1        2
             Diogo Jota    F M S     19      9        0
           Divock Origi      F S      9      0        0
                Fabinho    D M S     30      0        0
    Georginio Wijnaldum      M S     38      2        0
           James Milner    D M S     26      0        1
             Joel Matip      D S     10      1        2
       Jordan Henderson    D M S     21      1        1
           Joseph Gomez      D S      7      0        0
  Konstantinos Tsimikas        S      2      0        0
          Mohamed Salah    F M S     37     22        5
             Naby Keita      M S     10      0        0
     Nathaniel Phillips      D S     17      1        1
          Neco Williams      D S      6      0        0
             Ozan Kabak        D      9      0        0
          Rhys Williams      D S      9      0        0
        Roberto Firmino    F M S     36      9        7
             Sadio Mané    F M S     35     11        7
       Thiago Alcántara      M S     24      1        0
 Trent Alexander-Arnold      D S     36      2        7
        Virgil van Dijk        D      5      1        0
        Xherdan Shaqiri    F M S     14      0        2

### 8.Tampilkan semua pemain dari klub “Arsenal”

In [ ]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Filter pemain dari Arsenal
arsenal_players = df[df['team_title'] == 'Arsenal']

# Menampilkan kolom yang diinginkan (nama pemain dan informasi tambahan)
result = arsenal_players[['player_name', 'position', 'games', 'goals', 'assists']]

# Mengurutkan berdasarkan nama pemain
result_sorted = result.sort_values(by='player_name')

# Menampilkan hasil dengan format tabel rapi
print("DAFTAR PEMAIN ARSENAL MUSIM 2020/2021:")

print(result_sorted.to_string(index=False))

DAFTAR PEMAIN ARSENAL MUSIM 2020/2021:
              player_name position  games  goals  assists
      Alexandre Lacazette    F M S     30     13        2
               Bernd Leno       GK     34      0        0
              Bukayo Saka  D F M S     31      5        3
           Calum Chambers      D S      9      0        1
            Cédric Soares      D S     10      0        1
            Dani Ceballos      M S     25      0        3
               David Luiz      D S     20      1        0
            Eddie Nketiah      F S     17      2        1
         Emile Smith-Rowe      M S     19      2        4
                  Gabriel      D S     22      2        0
       Gabriel Martinelli    F M S     13      2        1
             Granit Xhaka    D M S     30      1        2
          Héctor Bellerín      D S     25      1        2
           Kieran Tierney      D S     26      1        3
          Martin Odegaard      M S     13      1        1
           Mohamed Elneny      M S     23      1        0
             Nicolas Pepe    F M S     28      8        1
               Pablo Marí        D     10      0        0
Pierre-Emerick Aubameyang    F M S     28     10        3
             Reiss Nelson        S      2      0        0
              Rob Holding      D S     29      0        1
     Rúnar Alex Rúnarsson        S      1      0        0
           Sead Kolasinac        D      1      0        0
         Shkodran Mustafi        S      3      0        0
            Thomas Partey      M S     23      0        2
                  Willian    F M S     25      1        5

### 9.Tampilkan 10 pemain yang memiliki jumlah kartu kuning paling banyak di EPL musim 2020/2021

In [ ]:
import pandas as pd

# Membaca dataset
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Mengambil kolom yang diperlukan dan mengurutkan berdasarkan kartu kuning
top_yellow_cards = df[['player_name', 'team_title', 'yellow_cards']] \
    .sort_values(by='yellow_cards', ascending=False) \
    .head(10)  # Ambil 10 teratas

# Format output
print("="*70)
print(f"{'TOP 10 PEMAIN DENGAN KARTU KUNING TERBANYAK (EPL 2020/2021)':^70}")
print("="*70)
print(top_yellow_cards.to_string(index=False))
print("="*70)

======================================================================
     TOP 10 PEMAIN DENGAN KARTU KUNING TERBANYAK (EPL 2020/2021)
======================================================================
          player_name           team_title  yellow_cards
          John McGinn          Aston Villa            12
      Conor Gallagher West Bromwich Albion            11
        Harry Maguire    Manchester United            11
      Kalvin Phillips                Leeds            10
Pierre-Emile Højbjerg            Tottenham             9
     Luka Milivojevic       Crystal Palace             8
         Isaac Hayden     Newcastle United             8
        Yves Bissouma             Brighton             8
       John Lundstram     Sheffield United             8
         Douglas Luiz          Aston Villa             8
======================================================================

### 10.Tampilkan 10 pemain yang memiliki jumlah kartu merah paling banyak di EPL musim 2020/2021

In [ ]:
import pandas as pd
from tabulate import tabulate

# Membaca dataset
df = pd.read_csv('epl-goalScorer(20-21).csv')

# Mengambil kolom yang diperlukan dan mengurutkan berdasarkan kartu merah
top_red_cards = df[['player_name', 'team_title', 'red_cards']] \
    .sort_values(by='red_cards', ascending=False) \
    .head(10)

# Membersihkan data (hapus pemain dengan 0 kartu merah)
top_red_cards = top_red_cards[top_red_cards['red_cards'] > 0]

# Format output
print("="*70)
print(f"{'TOP 10 PEMAIN DENGAN KARTU MERAH TERBANYAK (EPL 2020/2021)':^70}")
print("="*70)

# Cek apakah ada data kartu merah
if len(top_red_cards) > 0:
    print(tabulate(top_red_cards,
                 headers=['Nama Pemain', 'Klub', 'Kartu Merah'],
                 tablefmt='grid',
                 showindex=False))
else:
    print("Tidak ada pemain yang menerima kartu merah musim ini")

print("="*70)

======================================================================
      TOP 10 PEMAIN DENGAN KARTU MERAH TERBANYAK (EPL 2020/2021)
======================================================================
+---------------------+----------------------+---------------+
| Nama Pemain         | Klub                 |   Kartu Merah |
+=====================+======================+===============+
| Lewis Dunk          | Brighton             |             2 |
+---------------------+----------------------+---------------+
| Matthew Cash        | Aston Villa          |             1 |
+---------------------+----------------------+---------------+
| Antonee Robinson    | Fulham               |             1 |
+---------------------+----------------------+---------------+
| Christian Benteke   | Crystal Palace       |             1 |
+---------------------+----------------------+---------------+
| Matheus Pereira     | West Bromwich Albion |             1 |
+---------------------+----------------------+---------------+
| Alexandre Jankewitz | Southampton          |             1 |
+---------------------+----------------------+---------------+
| Tomas Soucek        | West Ham             |             1 |
+---------------------+----------------------+---------------+
| John Egan           | Sheffield United     |             1 |
+---------------------+----------------------+---------------+
| Ben White           | Brighton             |             1 |
+---------------------+----------------------+---------------+
| Matt Doherty        | Tottenham            |             1 |
+---------------------+----------------------+---------------+
======================================================================