<a href="https://colab.research.google.com/github/Afkar5115/Kecerdasan_Buatan_TI-1B_2025/blob/main/Jobsheet_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 7 Data Pre-processing

## Latihan

### 1.Data Preparation dengan One Hot Encoding

In [23]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Membuat data array gender
gender = ['perempuan', 'laki-laki', 'laki-laki', 'perempuan', 'perempuan']

# Membuat data frame dari data gender
df = pd.DataFrame({'gender': gender})

# Membuat instance dari OneHotEncoder (output berupa array, bukan sparse matrix)
encoder = OneHotEncoder(sparse_output=False)

# Melakukan encoding pada kolom 'gender'
encoded_array = encoder.fit_transform(df[['gender']])

# Membuat nama kolom dari hasil encoding
encoded_columns = encoder.get_feature_names_out(['gender'])

# Membuat DataFrame hasil encoding
encoded_df = pd.DataFrame(encoded_array, columns=encoded_columns)

# Menggabungkan data frame awal dengan hasil encoding
df_encoded = pd.concat([df, encoded_df], axis=1)

# Menampilkan hasil
print(df_encoded)

      gender  gender_laki-laki  gender_perempuan
0  perempuan               0.0               1.0
1  laki-laki               1.0               0.0
2  laki-laki               1.0               0.0
3  perempuan               0.0               1.0
4  perempuan               0.0               1.0

### 2.Data Preparation dengan Outlier Removal

In [2]:
import pandas as pd
import numpy as np

# membuat data frame contoh
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 20, 25, 30, 35, 40, 45, 50, 55, 500]
})

# mencari nilai z-score untuk setiap data point pada kolom B
z_scores = np.abs((df['B'] - df['B'].mean()) / df['B'].std())

# menghilangkan data point yang memiliki z-score lebih besar dari 3
df_clean = df.loc[round(z_scores) < 3]

# menampilkan data frame yang telah di-clean
print(df_clean)

   A   B
0  1  15
1  2  20
2  3  25
3  4  30
4  5  35
5  6  40
6  7  45
7  8  50
8  9  55

### 3.Data Preparation dengan Normalization

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
df

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   lala  0.75  0.25

### 4.Data Preparation dengan Standarization

In [7]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = StandardScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
df

    Nama      Gaji      Umur
0   Andi -1.612452 -1.364382
1   Budi -0.868243 -0.620174
2  Cindy -0.124035  0.124035
3  Diana  0.620174  0.868243
4    Eka  1.364382  1.612452
5   lala  0.620174 -0.620174

### 5.Pembuatan DataSet
A

In [8]:
from sklearn.model_selection import train_test_split
import pandas as pd

# membuat data frame contoh
df = pd.DataFrame({
    'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Y': [15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
})

# membagi data menjadi data latih dan data uji dengan rasio 80:20
X_train, X_test, y_train, y_test = train_test_split(df[['X']], df[['Y']], test_size=0.2, random_state=42)

# menampilkan data latih
print('Data Latih')
print('X_train:', X_train)
print('y_train:', y_train)

# menampilkan data uji
print('\nData Uji')
print('X_test:', X_test)
print('y_test:', y_test)

Data Latih
X_train:     X
5   6
0   1
7   8
2   3
9  10
4   5
3   4
6   7
y_train:     Y
5  40
0  15
7  50
2  25
9  60
4  35
3  30
6  45

Data Uji
X_test:    X
8  9
1  2
y_test:     Y
8  55
1  20

### B

In [20]:
from sklearn.model_selection import train_test_split
import pandas as pd

# Import data heart.csv
df = pd.read_csv('heart.csv');
df

# ambil 13 data dan masukan kedalam variabel data
data = df.iloc[:, :13]
data

# Rubah data ke array
data = data.values
data

# Masukan data pada kolom terakhir dan masukan kedalam variabel label
label = df.iloc[:, -1]

# Rubah data ke array
label = label.values
label

# Bagi data menjadi data training dan data testing
data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=0.2, random_state=42)

print('Ukuran data latih:', data_train.shape)
print('Ukuran data uji:', data_test.shape)

Ukuran data latih: (734, 12)
Ukuran data uji: (184, 12)

####  Cross Validation

In [26]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Memuat dataset contoh (Iris)
iris = load_iris()
X = iris.data       # Fitur
y = iris.target     # Label

# Membuat model Decision Tree
dt = DecisionTreeClassifier()

# Melakukan 5-fold cross validation
scores = cross_val_score(dt, X, y, cv=5)

# Menampilkan hasil cross validation secara rapi
print("Hasil 5-Fold Cross Validation:")
for i, score in enumerate(scores, 1):
    print(f"  Fold {i}: {score:.4f}")

print(f"\nRata-rata Akurasi: {scores.mean():.4f}")

Hasil 5-Fold Cross Validation:
  Fold 1: 0.9667
  Fold 2: 0.9667
  Fold 3: 0.9000
  Fold 4: 0.9667
  Fold 5: 1.0000

Rata-rata Akurasi: 0.9600

## TUGAS PRAKTIKUM

### Kemudian implementasikan teknik Data Preparation yang telah kalian pelajari dalam data tersebut

#### Data Preparation dengan One Hot Encoding

In [30]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Membaca data dari file CSV
data = pd.read_csv('/content/Data_Jabar.csv')

# Menampilkan informasi dasar tentang data
print("Informasi Data Awal:")
print(data.info())
print("\n5 Data Pertama:")
print(data.head())

# 1. Memilih kolom kategorikal untuk One Hot Encoding
# Kolom yang akan di-encode: nama_provinsi, nama_kabupaten_kota, nama_bpsk_dan_dinas, satuan
categorical_cols = ['nama_provinsi', 'nama_kabupaten_kota', 'nama_bpsk_dan_dinas', 'satuan']

# 2. Membuat One Hot Encoder
encoder = OneHotEncoder(sparse_output=False, drop='first')  # drop='first' untuk menghindari multicollinearity

# 3. Melakukan encoding pada kolom kategorikal
encoded_data = encoder.fit_transform(data[categorical_cols])

# 4. Membuat DataFrame dari hasil encoding
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

# 5. Menggabungkan data numerik dengan data yang sudah di-encode
# Kolom numerik: id, kode_provinsi, kode_kabupaten_kota, jumlah, tahun
numerical_data = data[['id', 'kode_provinsi', 'kode_kabupaten_kota', 'jumlah', 'tahun']]
final_data = pd.concat([numerical_data, encoded_df], axis=1)

# Menampilkan hasil
print("\nData setelah One Hot Encoding:")
print(final_data.head())

# Menyimpan data yang sudah diproses
final_data.to_csv('processed_consumer_complaints_data.csv', index=False)
print("\nData telah diproses dan disimpan sebagai 'processed_consumer_complaints_data.csv'")

Informasi Data Awal:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   36 non-null     int64
 1   kode_provinsi        36 non-null     int64
 2   nama_provinsi        36 non-null     object
 3   kode_kabupaten_kota  36 non-null     int64
 4   nama_kabupaten_kota  36 non-null     object
 5   nama_bpsk_dan_dinas  36 non-null     object
 6   jumlah               36 non-null     int64
 7   satuan               36 non-null     object
 8   tahun                36 non-null     int64
dtypes: int64(5), object(4)
memory usage: 2.7+ KB
None

5 Data Pertama:
   id  kode_provinsi nama_provinsi  kode_kabupaten_kota nama_kabupaten_kota  \
0   1             32    JAWA BARAT                 3201     KABUPATEN BOGOR
1   2             32    JAWA BARAT                 3202  KABUPATEN SUKABUMI
2   3             32    JAWA BARAT                 3203   KABUPATEN CIANJUR
3   4             32    JAWA BARAT                 3204   KABUPATEN BANDUNG
4   5             32    JAWA BARAT                 3205     KABUPATEN GARUT

       nama_bpsk_dan_dinas  jumlah satuan  tahun
0     BPSK KABUPATEN BOGOR      42  KASUS   2023
1  BPSK KABUPATEN SUKABUMI      22  KASUS   2023
2   BPSK KABUPATEN CIANJUR      35  KASUS   2023
3   BPSK KABUPATEN BANDUNG      39  KASUS   2023
4     BPSK KABUPATEN GARUT      26  KASUS   2023

Data setelah One Hot Encoding:
   id  kode_provinsi  kode_kabupaten_kota  jumlah  tahun  \
0   1             32                 3201      42   2023
1   2             32                 3202      22   2023
2   3             32                 3203      35   2023
3   4             32                 3204      39   2023
4   5             32                 3205      26   2023

   nama_kabupaten_kota_KABUPATEN BOGOR  nama_kabupaten_kota_KABUPATEN CIANJUR  \
0                                  1.0                                    0.0
1                                  0.0                                    0.0
2                                  0.0                                    1.0
3                                  0.0                                    0.0
4                                  0.0                                    0.0

   nama_kabupaten_kota_KABUPATEN CIREBON  nama_kabupaten_kota_KABUPATEN GARUT  \
0                                    0.0                                  0.0
1                                    0.0                                  0.0
2                                    0.0                                  0.0
3                                    0.0                                  0.0
4                                    0.0                                  1.0

   nama_kabupaten_kota_KABUPATEN INDRAMAYU  ...  \
0                                      0.0  ...
1                                      0.0  ...
2                                      0.0  ...
3                                      0.0  ...
4                                      0.0  ...

   nama_bpsk_dan_dinas_BPSK KABUPATEN SUKABUMI  \
0                                          0.0
1                                          1.0
2                                          0.0
3                                          0.0
4                                          0.0

   nama_bpsk_dan_dinas_BPSK KABUPATEN SUMEDANG  \
0                                          0.0
1                                          0.0
2                                          0.0
3                                          0.0
4                                          0.0

   nama_bpsk_dan_dinas_BPSK KOTA BANDUNG  \
0                                    0.0
1                                    0.0
2                                    0.0
3                                    0.0
4                                    0.0

   nama_bpsk_dan_dinas_BPSK KOTA BEKASI  nama_bpsk_dan_dinas_BPSK KOTA BOGOR  \
0                                   0.0                                  0.0
1                                   0.0                                  0.0
2                                   0.0                                  0.0
3                                   0.0                                  0.0
4                                   0.0                                  0.0

   nama_bpsk_dan_dinas_BPSK KOTA CIREBON  \
0                                    0.0
1                                    0.0
2                                    0.0
3                                    0.0
4                                    0.0

   nama_bpsk_dan_dinas_BPSK KOTA SUKABUMI  \
0                                     0.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0

   nama_bpsk_dan_dinas_BPSK KOTA TASIKMALAYA  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0

   nama_bpsk_dan_dinas_DISIPERINDAG JABAR  \
0                                     0.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0

   nama_bpsk_dan_dinas_DISPERINDAG JABAR
0                                    0.0
1                                    0.0
2                                    0.0
3                                    0.0
4                                    0.0

[5 rows x 40 columns]

Data telah diproses dan disimpan sebagai 'processed_consumer_complaints_data.csv'

#### Data Preparation dengan Outlier Removal

In [32]:
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv('/content/Data_Jabar.csv')

# Function to display data in clean tabular format
def display_clean(df, title=""):
    print(f"\n{title}")
    print(df.to_string(index=False))
    print(f"({len(df)} rows)")

# Data Exploration
display_clean(data.head(10), "Data Overview (First 10 rows):")

# Check for missing values
missing_values = data.isnull().sum().to_frame().reset_index()
missing_values.columns = ['Column', 'Missing Values']
display_clean(missing_values, "Missing Values Check:")

# Outlier Detection and Removal using IQR method
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Filter the DataFrame
    filtered_df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    display_clean(outliers[['nama_kabupaten_kota', 'tahun', 'jumlah']], "Outliers Removed:")

    return filtered_df

# Remove outliers
clean_data = remove_outliers(data, 'jumlah')

# Compare statistics before and after
stats_before = data['jumlah'].describe().to_frame().reset_index()
stats_before.columns = ['Statistic', 'Before']
stats_after = clean_data['jumlah'].describe().to_frame().reset_index()
stats_after.columns = ['Statistic', 'After']
stats_comparison = pd.merge(stats_before, stats_after, on='Statistic')
display_clean(stats_comparison, "Statistics Comparison (Before vs After Outlier Removal):")


# Save cleaned data
clean_data.to_csv('cleaned_consumer_complaints_data.csv', index=False)
print("\nCleaned data saved to 'cleaned_consumer_complaints_data.csv'")

Data Overview (First 10 rows):
 id  kode_provinsi nama_provinsi  kode_kabupaten_kota  nama_kabupaten_kota       nama_bpsk_dan_dinas  jumlah satuan  tahun
  1             32    JAWA BARAT                 3201      KABUPATEN BOGOR      BPSK KABUPATEN BOGOR      42  KASUS   2023
  2             32    JAWA BARAT                 3202   KABUPATEN SUKABUMI   BPSK KABUPATEN SUKABUMI      22  KASUS   2023
  3             32    JAWA BARAT                 3203    KABUPATEN CIANJUR    BPSK KABUPATEN CIANJUR      35  KASUS   2023
  4             32    JAWA BARAT                 3204    KABUPATEN BANDUNG    BPSK KABUPATEN BANDUNG      39  KASUS   2023
  5             32    JAWA BARAT                 3205      KABUPATEN GARUT      BPSK KABUPATEN GARUT      26  KASUS   2023
  6             32    JAWA BARAT                 3208   KABUPATEN KUNINGAN   BPSK KABUPATEN KUNINGAN      34  KASUS   2023
  7             32    JAWA BARAT                 3209    KABUPATEN CIREBON    BPSK KABUPATEN CIREBON       7  KASUS   2023
  8             32    JAWA BARAT                 3211   KABUPATEN SUMEDANG   BPSK KABUPATEN SUMEDANG      32  KASUS   2023
  9             32    JAWA BARAT                 3212  KABUPATEN INDRAMAYU  BPSK KABUPATEN INDRAMAYU      17  KASUS   2023
 10             32    JAWA BARAT                 3214 KABUPATEN PURWAKARTA BPSK KABUPATEN PURWAKARTA      35  KASUS   2023
(10 rows)

Missing Values Check:
             Column  Missing Values
                 id               0
      kode_provinsi               0
      nama_provinsi               0
kode_kabupaten_kota               0
nama_kabupaten_kota               0
nama_bpsk_dan_dinas               0
             jumlah               0
             satuan               0
              tahun               0
(9 rows)

Outliers Removed:
nama_kabupaten_kota  tahun  jumlah
 KABUPATEN KARAWANG   2024     110
(1 rows)

Statistics Comparison (Before vs After Outlier Removal):
Statistic     Before     After
    count  36.000000 35.000000
     mean  42.944444 41.028571
      std  26.164255 23.846921
      min   4.000000  4.000000
      25%  22.000000 22.000000
      50%  39.000000 39.000000
      75%  55.250000 53.500000
      max 110.000000 98.000000
(8 rows)

Cleaned data saved to 'cleaned_consumer_complaints_data.csv'

#### 	Data Preparation dengan Normalization

In [34]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load the data
data = pd.read_csv('/content/Data_Jabar.csv')

# Create a copy for normalization
normalized_data = data.copy()

# Min-Max Normalization
min_max_scaler = MinMaxScaler()
normalized_data['jumlah_minmax'] = min_max_scaler.fit_transform(data[['jumlah']])

# Z-score Normalization
z_scaler = StandardScaler()
normalized_data['jumlah_zscore'] = z_scaler.fit_transform(data[['jumlah']])

# Display only the normalized data sample
print("=== Normalized Data (Sample) ===")
print(normalized_data[['nama_kabupaten_kota', 'tahun', 'jumlah', 'jumlah_minmax', 'jumlah_zscore']].head(10))

=== Normalized Data (Sample) ===
    nama_kabupaten_kota  tahun  jumlah  jumlah_minmax  jumlah_zscore
0       KABUPATEN BOGOR   2023      42       0.358491      -0.036609
1    KABUPATEN SUKABUMI   2023      22       0.169811      -0.811854
2     KABUPATEN CIANJUR   2023      35       0.292453      -0.307944
3     KABUPATEN BANDUNG   2023      39       0.330189      -0.152895
4       KABUPATEN GARUT   2023      26       0.207547      -0.656805
5    KABUPATEN KUNINGAN   2023      34       0.283019      -0.346707
6     KABUPATEN CIREBON   2023       7       0.028302      -1.393287
7    KABUPATEN SUMEDANG   2023      32       0.264151      -0.424231
8   KABUPATEN INDRAMAYU   2023      17       0.122642      -1.005665
9  KABUPATEN PURWAKARTA   2023      35       0.292453      -0.307944

#### 	Data Preparation dengan Standarization

In [36]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load the dataset
data = pd.read_csv('/content/Data_Jabar.csv')

# Select relevant columns
df = data[['nama_kabupaten_kota', 'jumlah', 'tahun']].copy()

# Initialize the StandardScaler
scaler = StandardScaler()

# Add standardized column
df['jumlah_standardized'] = df.groupby('tahun')['jumlah'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)

# Display only the standardized data (sorted by year and region)
standardized_output = df[['nama_kabupaten_kota', 'tahun', 'jumlah', 'jumlah_standardized']].sort_values(
    ['tahun', 'nama_kabupaten_kota']
)

print("Standardized Data:")
print(standardized_output.to_string(index=False))

# Save the standardized data to a new CSV file
standardized_output.to_csv('standardized_consumer_complaints.csv', index=False)
print("\nData telah disimpan ke 'standardized_consumer_complaints.csv'")

Standardized Data:
 nama_kabupaten_kota  tahun  jumlah  jumlah_standardized
   KABUPATEN BANDUNG   2023      39             0.058810
     KABUPATEN BOGOR   2023      42             0.180955
   KABUPATEN CIANJUR   2023      35            -0.104049
   KABUPATEN CIREBON   2023       7            -1.244064
     KABUPATEN GARUT   2023      26            -0.470482
 KABUPATEN INDRAMAYU   2023      17            -0.836916
  KABUPATEN KARAWANG   2023      96             2.379555
  KABUPATEN KUNINGAN   2023      34            -0.144764
KABUPATEN PURWAKARTA   2023      35            -0.104049
  KABUPATEN SUKABUMI   2023      22            -0.633342
  KABUPATEN SUMEDANG   2023      32            -0.226193
        KOTA BANDUNG   2023      29            -0.348338
         KOTA BEKASI   2023      57             0.791677
          KOTA BOGOR   2023      39             0.058810
        KOTA CIREBON   2023      45             0.303099
       KOTA SUKABUMI   2023      19            -0.755486
    KOTA TASIKMALAYA   2023      98             2.460984
 PROVINSI JAWA BARAT   2023       4            -1.366208
   KABUPATEN BANDUNG   2024      55             0.257599
     KABUPATEN BOGOR   2024      66             0.682636
   KABUPATEN CIANJUR   2024      19            -1.133434
   KABUPATEN CIREBON   2024      10            -1.481192
     KABUPATEN GARUT   2024      48            -0.012880
 KABUPATEN INDRAMAYU   2024      51             0.103039
  KABUPATEN KARAWANG   2024     110             2.382786
  KABUPATEN KUNINGAN   2024      43            -0.206079
KABUPATEN PURWAKARTA   2024      48            -0.012880
  KABUPATEN SUKABUMI   2024      52             0.141679
  KABUPATEN SUMEDANG   2024      31            -0.669756
        KOTA BANDUNG   2024      70             0.837195
         KOTA BEKASI   2024      90             1.609991
          KOTA BOGOR   2024      56             0.296238
        KOTA CIREBON   2024      20            -1.094794
       KOTA SUKABUMI   2024      22            -1.017514
    KOTA TASIKMALAYA   2024      65             0.643996
 PROVINSI JAWA BARAT   2024      14            -1.326632

Data telah disimpan ke 'standardized_consumer_complaints.csv'

#### Pembuatan DataSet

In [37]:
import pandas as pd

# Data dari file CSV
data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
           19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
    'kode_provinsi': [32]*36,
    'nama_provinsi': ['JAWA BARAT']*36,
    'kode_kabupaten_kota': [3201, 3202, 3203, 3204, 3205, 3208, 3209, 3211, 3212, 3214,
                            3215, 3271, 3272, 3273, 3274, 3275, 3278, 3200,
                            3201, 3202, 3203, 3204, 3205, 3208, 3209, 3211, 3212, 3214,
                            3215, 3271, 3272, 3273, 3274, 3275, 3278, 3200],
    'nama_kabupaten_kota': ['KABUPATEN BOGOR', 'KABUPATEN SUKABUMI', 'KABUPATEN CIANJUR',
                           'KABUPATEN BANDUNG', 'KABUPATEN GARUT', 'KABUPATEN KUNINGAN',
                           'KABUPATEN CIREBON', 'KABUPATEN SUMEDANG', 'KABUPATEN INDRAMAYU',
                           'KABUPATEN PURWAKARTA', 'KABUPATEN KARAWANG', 'KOTA BOGOR',
                           'KOTA SUKABUMI', 'KOTA BANDUNG', 'KOTA CIREBON', 'KOTA BEKASI',
                           'KOTA TASIKMALAYA', 'PROVINSI JAWA BARAT']*2,
    'nama_bpsk_dan_dinas': ['BPSK KABUPATEN BOGOR', 'BPSK KABUPATEN SUKABUMI',
                           'BPSK KABUPATEN CIANJUR', 'BPSK KABUPATEN BANDUNG',
                           'BPSK KABUPATEN GARUT', 'BPSK KABUPATEN KUNINGAN',
                           'BPSK KABUPATEN CIREBON', 'BPSK KABUPATEN SUMEDANG',
                           'BPSK KABUPATEN INDRAMAYU', 'BPSK KABUPATEN PURWAKARTA',
                           'BPSK KABUPATEN KARAWANG', 'BPSK KOTA BOGOR',
                           'BPSK KOTA SUKABUMI', 'BPSK KOTA BANDUNG', 'BPSK KOTA CIREBON',
                           'BPSK KOTA BEKASI', 'BPSK KOTA TASIKMALAYA', 'DISPERINDAG JABAR',
                           'BPSK KABUPATEN BOGOR', 'BPSK KABUPATEN SUKABUMI',
                           'BPSK KABUPATEN CIANJUR', 'BPSK KABUPATEN BANDUNG',
                           'BPSK KABUPATEN GARUT', 'BPSK KABUPATEN KUNINGAN',
                           'BPSK KABUPATEN CIREBON', 'BPSK KABUPATEN SUMEDANG',
                           'BPSK KABUPATEN INDRAMAYU', 'BPSK KABUPATEN PURWAKARTA',
                           'BPSK KABUPATEN KARAWANG', 'BPSK KOTA BOGOR',
                           'BPSK KOTA SUKABUMI', 'BPSK KOTA BANDUNG', 'BPSK KOTA CIREBON',
                           'BPSK KOTA BEKASI', 'BPSK KOTA TASIKMALAYA', 'DISIPERINDAG JABAR'],
    'jumlah': [42, 22, 35, 39, 26, 34, 7, 32, 17, 35, 96, 39, 19, 29, 45, 57, 98, 4,
               66, 52, 19, 55, 48, 43, 10, 31, 51, 48, 110, 56, 22, 70, 20, 90, 65, 14],
    'satuan': ['KASUS']*36,
    'tahun': [2023]*18 + [2024]*18
}

# Membuat DataFrame
df = pd.DataFrame(data)

# Menampilkan 5 baris pertama
print("Preview Dataset:")
print(df.head())

# Menyimpan ke file CSV
df.to_csv('pengaduan_konsumen_jabar.csv', index=False)
print("\nDataset telah disimpan sebagai 'pengaduan_konsumen_jabar.csv'")

# Analisis sederhana
print("\nAnalisis Data:")
total_2023 = df[df['tahun'] == 2023]['jumlah'].sum()
total_2024 = df[df['tahun'] == 2024]['jumlah'].sum()
print(f"Total kasus terselesaikan tahun 2023: {total_2023} kasus")
print(f"Total kasus terselesaikan tahun 2024: {total_2024} kasus")
print(f"Kenaikan/Penurunan: {total_2024 - total_2023} kasus ({((total_2024 - total_2023)/total_2023)*100:.2f}%)")

# Kabupaten/Kota dengan kasus terbanyak tahun 2024
max_2024 = df[df['tahun'] == 2024].loc[df['jumlah'].idxmax()]
print(f"\nKabupaten/Kota dengan kasus terbanyak tahun 2024: {max_2024['nama_kabupaten_kota']} ({max_2024['jumlah']} kasus)")

Preview Dataset:
   id  kode_provinsi nama_provinsi  kode_kabupaten_kota nama_kabupaten_kota  \
0   1             32    JAWA BARAT                 3201     KABUPATEN BOGOR
1   2             32    JAWA BARAT                 3202  KABUPATEN SUKABUMI
2   3             32    JAWA BARAT                 3203   KABUPATEN CIANJUR
3   4             32    JAWA BARAT                 3204   KABUPATEN BANDUNG
4   5             32    JAWA BARAT                 3205     KABUPATEN GARUT

       nama_bpsk_dan_dinas  jumlah satuan  tahun
0     BPSK KABUPATEN BOGOR      42  KASUS   2023
1  BPSK KABUPATEN SUKABUMI      22  KASUS   2023
2   BPSK KABUPATEN CIANJUR      35  KASUS   2023
3   BPSK KABUPATEN BANDUNG      39  KASUS   2023
4     BPSK KABUPATEN GARUT      26  KASUS   2023

Dataset telah disimpan sebagai 'pengaduan_konsumen_jabar.csv'

Analisis Data:
Total kasus terselesaikan tahun 2023: 676 kasus
Total kasus terselesaikan tahun 2024: 870 kasus
Kenaikan/Penurunan: 194 kasus (28.70%)

Kabupaten/Kota dengan kasus terbanyak tahun 2024: KABUPATEN KARAWANG (110 kasus)